### ISSUE TITLE
QA Server- Tag-1.0083-Start Reasoner-Receive Error

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#325] opened 2017-08-31 23:22 UTC
Hi, 
The Start Reasoning and restarted the Remote Reasoner successfully. But when reclogging back into the Protégé, I received errors. Please see attached screenshot and log file for more details.

[protege-QA-Server-8.31.2017.txt](https://github.com/NCIEVS/nci-protege5/files/1268752/protege-QA-Server-8.31.2017.txt)

![qa-server_start reasoner-error](https://user-images.githubusercontent.com/8367102/29949282-abfa12bc-8e81-11e7-928a-7196f73ca030.png)

Uncaught Exception in thread 'AWT-EventQueue-0' 
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Request call failed: [500] Internal Server Error
                at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava.jar:na]
                at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava.jar:na]
                at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava.jar:na]
                at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[ 

Thanks,
Reza

**Comment by bdionne** [comment] 2017-08-31 23:30
Tracy reported a similar issue - @rmehri when you see `500` errors like this they indicate a server problem:

````

2017-08-31 19:02:30.740 [AWT-EventQueue-0] ERROR OWLCellRenderer    An error occurred whilst rendering a token. Token: owl:Thing; Token start index: 0
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Request call failed: [500] Internal Server Error
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava.jar:na]
	at com.complexible.pellet.client.reasoner.RemoteSchemaReasoner.query(RemoteSchemaReasoner.java:65) ~[na:na]

````

If you could also attach any pellet server logs or capture the console that would be helpful, we could see what the issue is

**Comment by bdionne** [comment] 2017-09-01 10:30
Hi Reza,

I meant the pellet server log

Thanks,

Bob

**Comment by safrant** [comment] 2017-09-01 13:26
I've included the pellet logs from Dev (where I was testing) and QA.  They don't seem very revealing.

[pellet-console_QA.txt](https://github.com/NCIEVS/nci-protege5/files/1270342/pellet-console_QA.txt)


[pellet-console_DEV.txt](https://github.com/NCIEVS/nci-protege5/files/1270337/pellet-console_DEV.txt)

**Comment by NCIEVS** [comment] 2018-01-23 21:32
the 500 is not very explanatory, however pellet is in production so the issue has probably been fixed indirectly, OBE.

**Closed by NCIEVS** 2018-01-23 21:32 UTC
Labels: needs investigation
