### ISSUE TITLE
Perform Multiple Edits - Primitive To Defined - Client Frozen 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#478] opened 2020-10-13 19:39 UTC

**Comment by safrant** [comment] 2020-10-13 19:50
Created 3 concepts - under Nodular Oncocytic Hyperplasia (C173663). 
NOH Sub 1
NOH Sub 2
NOH Sub 3

Made NOH Sub 2 a child of NOH Sub 1
Added role "Disease_Has_Abnormal_Cell some Test_8" to both NOH Sub 1 and NOH Sub 3
Converted NOH Sub 1 to Defined.  NOH Sub 3 made equivalent, which I expected.

Problem 1: Clicking on NOH Sub 2 in the Navigation Hierarchy causes the application to hang for about 20 seconds.

Problem 2: Clicking on NOH sub1 and choosing to convert it back to primitive gives an error that this would result in multiple disjoint roots. Saving anyway throws NOH Sub 3 into the root of the ontology.  NOH Sub 1 is treed underneath it, and dual treed under Nodular Oncocytic Hyperplasia.

**Comment by singhik** [comment] 2020-10-13 20:04
@bdionne : Hi, what information is required from our end for this ticket ?

**Comment by bdionne** [comment] 2020-10-13 20:22
@singhik @safrant - so what's the bug? Did the client freeze or just hang for 20 secs?

@safrant - I'll try this, what is `Test_8` ?

Also, what is the issue, and what is it you are expecting to see here? The example seems to confuse  `NOH Sub 2` and `NOH Sub 3`

> Converted NOH Sub 1 to Defined. NOH Sub 3 made equivalent, which I expected.
? can you clarify this?

**Comment by safrant** [comment] 2020-10-13 20:31
NOH Sub 1 and NOH Sub 3 were siblings with the same set of restrictions.  When I made NOH Sub 1 defined, NOH Sub 3 was automatically made equivalent.  This is what I would expect to happen.

The first issue is that NOH Sub 2, a child of NOH Sub 1, now takes half a minute to open.

The second issue is that flipping "the NOH Sub 1 Equivalent NOH Sub 3" pair back to primitive sends the NOH Sub 3 to the root of the ontology with NOH Sub 1 as a child.  I am not sure what this should be doing, that is up to Gilberto. I just think the behavior is odd and wanted to make a note of it.

**Comment by bdionne** [comment] 2020-10-13 20:39
> When I made NOH Sub 1 defined, NOH Sub 3 was automatically made equivalent. This is what I would expect to happen.

I'm not sure about this, `'Sub 3` might go under it but not Eq, and that would be after classification. I need to see the example more clearly.

What is `Test_8`? Is it just any primitive that fits the type of the filler for that role?

Thanks

**Comment by safrant** [comment] 2020-10-13 21:07
Yes, Test_8 is a primitive filler, but was among the set of classes that Itendra was working on.
The equivalency occurred immediately upon save.  

I have tried replicating but now I am getting equivalency with the parent. probably because I haven't got the steps exactly the same. 
Here is the initial state of the concepts:

![Screen Shot 2020-10-13 at 4 59 09 PM](https://user-images.githubusercontent.com/2364871/95916082-1e43e480-0d76-11eb-86a6-c98af9282bdf.png)
![Screen Shot 2020-10-13 at 4 58 59 PM](https://user-images.githubusercontent.com/2364871/95916083-1edc7b00-0d76-11eb-88ac-5851219daa15.png)
![Screen Shot 2020-10-13 at 4 58 49 PM](https://user-images.githubusercontent.com/2364871/95916084-1edc7b00-0d76-11eb-8b4c-8da24f23b250.png)
![Screen Shot 2020-10-13 at 4 58 34 PM](https://user-images.githubusercontent.com/2364871/95916085-1edc7b00-0d76-11eb-8b70-611af59f848f.png)

I then converted NOH Sub 1 to defined
![Screen Shot 2020-10-13 at 4 59 24 PM](https://user-images.githubusercontent.com/2364871/95916133-30be1e00-0d76-11eb-90a9-0b3af6db3fcf.png)

And immediately Nodular Oncocytic Hyperplasia is equivalent, and this time they are at the root immediately
![Screen Shot 2020-10-13 at 4 59 33 PM](https://user-images.githubusercontent.com/2364871/95916290-682cca80-0d76-11eb-9d02-c2754128db23.png)

**Comment by safrant** [comment] 2020-10-13 21:11
[protege.log](https://github.com/NCIEVS/nci-protege5/files/5374150/protege.log)
[console.txt](https://github.com/NCIEVS/nci-protege5/files/5374157/console.txt)

**Comment by bdionne** [comment] 2020-10-13 21:31
I see, @safrant in this second example, you made `Sub 1` defined, but hadn't added a role to it, you hadded a role to `Sub 2` so `Sub1` will immediately be `EQ` to it's parent, and it has not other parent so it goes to the top.

I'm pretty sure that's correct, though it might be a modelling error we want to prevent the user from doing.

I tried your first example as stated above and the classifier did put `Sub 3` under `Sub 1` as I thought. I didn't seeing any hanging on `Sub 2`, but that might be related to your use of `Test_8` and concurrent editing.

> Classifying while in this state resulted in "System Overflow Error"

I'll look into this

**Comment by bdionne** [comment] 2020-10-14 18:50
>Classifying while in this state resulted in "System Overflow Error"

@safrant - this is a bug and is being addressed in #479

**Comment by bdionne** [comment] 2020-10-19 16:41
Should we close this? 

cc: @safrant @NCIEVS

**Comment by safrant** [comment] 2020-10-19 16:49
It sounds like a duplicate of 479, so yes.  I will close

**Closed by safrant** 2020-10-19 16:49 UTC
Labels: needs investigation

**Comment by bdionne** [comment] 2020-10-20 14:34
Thanks @safrant , yea I opened #479 because it's a separate issue, easily reproduced, and orthogonal to this one. There's also another issue, that the user shouldn't be allowed to do this conversion, and we have a ticket for that also, #481.
