### ISSUE TITLE
classification issue

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#425] opened 2019-07-15 19:53 UTC
We've reached the point where the size of NCI Thesaurus is such that classification performance is beginning to degrade. It's anticipated that with current growth rates that this will only worsen.

It's been observed that modelers generally use a much smaller subset of the OWL DL supported features and that those features could be supported as extensions to the editing process, for example detecting that the addition of a new parent creates inconsistencies.

The goal is to support classification as part of the editing process that accommodates the most common workflow, where a modeler makes changes, sees that new axioms are inferred, and then adds those axioms so that a reclassification produces no new results.

This will be supplemented by an additional full classification during the publish phase when the workflow managers are reviewing and committing or rejecting changes

**Comment by singhik** [comment] 2020-06-25 19:32
@bdionne :: 'Curator' is  a new functionality that is added and needs to be tested . More details to be added .

**Comment by NCIEVS** [comment] 2020-07-02 14:54
Noting what the classifier needs to support and what it can ignore.

Support:
sub-class
equivalent-class
existential restriction
union
intersection
disjointness
transitive properties
sub-objectproperties
objectproperty domains & ranges

Ignore:
universal restriction
negation
restrictions on datatypes
individuals
oneOf
general concept inclusion
cardinality
qualified cardinality
property chains
property equivalency, disjointness, functional, inverse, inverse functional, symmetric, asymmetric, reflexive, irreflexive, subdatatype

**Comment by singhik** [comment] 2020-07-02 17:34
From @bdionne  :: 
"I can reliably reproduce one of these reported freezes, using a smaller ontology and a somewhat contrived setup. We've know all along that the issue is the extremely long path length of the code in the autoupdater.
I have a possible fix which will be in the next protégé build. It's not a real solution but is worth a try if it stops the freezes."

**Comment by singhik** [comment] 2020-07-31 19:49
@bdionne : In 3.4.0-qa2 

 Warning prompt Pop-Ups for Disjoint and Redundant concept does not appear ::

![image](https://user-images.githubusercontent.com/36314371/89071406-a48a8600-d344-11ea-8631-44095030d5a8.png)

![image](https://user-images.githubusercontent.com/36314371/89071417-ac4a2a80-d344-11ea-9d68-746f90465407.png)

**Comment by singhik** [comment] 2020-08-04 20:30
@bdionne : #445, for the Inference Results refresh panel issue post Curator preferences are changed, applies to this ticket as well .

**Comment by singhik** [comment] 2020-08-07 15:31
Classification has been tested on 3.4.0-qa2 ,hence closing the ticket .

**Closed by singhik** 2020-08-07 15:31 UTC
Labels: enhancement, needs user input, pass
