### ISSUE TITLE
creation of required properties in batch edits

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#170] opened 2017-01-06 19:05 UTC
Applies to annotations as well as qualifiers (annotations on annotations).

Already done in "manual" mode, how to identify in a batch?
- immutable: only software can set values on creation
- required:  software or user must set a value before a Save
- default:  if not specified, a "required" property is assigned a default value

Set for V1, but can be reconsidered for future release.

**Comment by rmehri** [comment] 2017-02-09 18:57
Hi, 
I have retested using tag-120, edittab-0.3.7.  The log file indicates that the batch test results were successful but the qualifiers did not get into protégé GUI.   Please see attached zip file for screen shot and batch files for more details. 

[Add Qualifier_2.zip](https://github.com/NCIEVS/nci-protege5/files/764698/Add.Qualifier_2.zip)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-02-10 17:33
Are you sure they didn't get added, sometimes depending on where you are the panel doesn't immediately refresh form the batch edit. Clicking away and coming back will refresh.

Also, looking at your input file, you have some whitespace errors in some of the qualifiers. If you set the delimiter to the tab key, `\t`, then you have to be sure and use that to separate the fields, not plain old spaces. Some of the windows based editors are awkward in this regard.

**Comment by rmehri** [comment] 2017-02-10 18:13
Hi Bob, 
Thanks for your feedback! Yes I have tried them at the time of testing that did not help.  I will retest them again. 
Reza

**Comment by bdionne** [comment] 2017-02-10 18:18
I think you need to fix your input file. I tried the one you attached and it fails, because the invalid whitespace causes it to parse qualifiers that don't exist

**Comment by rmehri** [comment] 2017-02-10 18:21
Hi Bob, 
I am looking into that now. 
Thanks,
Reza

**Comment by rmehri** [comment] 2017-02-10 20:07
Hi Bob, 

I have retested the batch file using tag-120, edittab-03.9 and received the same results.  I also tested manually and tried to add FULL_SYN to a concept that did not add qualifiers either.  Only term source's value is added.  Please see attached zip file for the video to play, screen shot, and input and out batch files for more details.  

[RMV3-FULL_SYN-Tag-120.zip](https://github.com/NCIEVS/nci-protege5/files/767670/RMV3-FULL_SYN-Tag-120.zip)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-02-10 21:20
@rmehri - there is still some bad whitespace in this file, in both records a single space before the `term-source`. The qualifier is than interpreted as ` term-source` which doesn't exist. If you fix that and run the file you'll see:

<img width="1023" alt="screen shot 2017-02-10 at 4 15 54 pm" src="https://cloud.githubusercontent.com/assets/31741/22844544/ce24ddbe-efac-11e6-93fc-25bfc7d9d867.png">

**Comment by rmehri** [comment] 2017-02-10 23:10
Hi, 
I have retested this and see the same issue.  Apparently, there is a problem with adding the FULL_SYN qualifiers to a concept manually as well as the batch.  This is strange!  Anyhow, I recorded the behavior for the clarity of this problem. Please see attached zip file to play the video. By the way, are you using edittab-0.3.9 on your machine? Also, I need to test this using  development server "https://nciws-d699-v.nci.nih.gov:9090". Currently, this server is showing in maintenance mode. I will try this later.

[Add FULL_SYN_Qualifiers.zip](https://github.com/NCIEVS/nci-protege5/files/767986/Add.FULL_SYN_Qualifiers.zip)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-02-10 23:42
Did you fix the whitespace errors in your input. Please attach the input file so I can try to reproduce it.

**Comment by rmehri** [comment] 2017-02-14 20:23
Hi Bob, 
Yes I did.  I retested this issue using tab space with and without comma, which resulted with the different test results.  Please see attached batch files for more details and  let me know if you need more information. 

[RMv6-Def-With With Comma Tag-120.txt](https://github.com/NCIEVS/nci-protege5/files/775203/RMv6-Def-With.With.Comma.Tag-120.txt)
[RMv6-Def-With With Comma Tag-120-Out.txt](https://github.com/NCIEVS/nci-protege5/files/775202/RMv6-Def-With.With.Comma.Tag-120-Out.txt)

[RMv6-Def-Tag-120.txt](https://github.com/NCIEVS/nci-protege5/files/775204/RMv6-Def-Tag-120.txt)
[RMv6-Def-Tag-120-Out.txt](https://github.com/NCIEVS/nci-protege5/files/775205/RMv6-Def-Tag-120-Out.txt)

*Note: also, adding definition manually to protégé, the qualifies do not get added either.  

Thanks,
Reza

**Comment by bdionne** [comment] 2017-02-14 21:04
@rmehri - Both of these input files have the same issue, a spurious tab inside the definition text right after the word `The` and in the second record an extra tab at the end of the line followed by another newline. In the second record the software looks for more qualifier. The qualifiers come in pairs, .eg. `term-source NCI` so it's important to make sure you have field delimiters between pairs. What happened is that the additional tab inside the definition causes the array index out of bounds and the record fails to load.

If you try this file, which fixes the tab problem:

[RMv6-Def-Quals.txt](https://github.com/NCIEVS/nci-protege5/files/775276/RMv6-Def-Quals.txt)

The records will load, but now you will see errors processing. This is because `Definition_Reviewer_Name` and `Definition_Review_Date` are immutable (read-only) and get automatically added. It's the same when you manually edit a definition, the editor who is logged in and the current date are used for those qualifiers. So if you remove those two qualifiers:

[RMv6-Def-Quals2.txt](https://github.com/NCIEVS/nci-protege5/files/775279/RMv6-Def-Quals2.txt)

You should see it work. Note that I changed the class id to match something in my ontology:

<img width="1014" alt="screen shot 2017-02-14 at 3 48 21 pm" src="https://cloud.githubusercontent.com/assets/31741/22949125/22c2866c-f2cf-11e6-840c-3799f920e1e1.png">

I use emacs to edit these files, which lets me see whitespace, I would imagine notepad has something similar.

**Comment by rmehri** [comment] 2017-02-14 22:54
Hi Bob, 
Thanks for your feedback! I have used the corrected batch file and changed the concept and test result was successful. But the protégé GUI is still showing missing values on my local machine.  
[RMv6-Def-Quals2-Good.txt](https://github.com/NCIEVS/nci-protege5/files/775505/RMv6-Def-Quals2-Good.txt)
[RMv6-Def-Quals2-Good-Out.txt](https://github.com/NCIEVS/nci-protege5/files/775506/RMv6-Def-Quals2-Good-Out.txt)

![add_definition_batchfile_missing values](https://cloud.githubusercontent.com/assets/8367102/22953159/06861004-f2de-11e6-91e9-90eabca48ced.png)

I also manually added definition to one of the concepts, which resulted with the missing  definition review name and definition review date  on my local server. 

![add_definition_manually_missing values](https://cloud.githubusercontent.com/assets/8367102/22953277/7de9cc4e-f2de-11e6-8f14-15a2b78a4189.png)

I will retest these on the different workstation. 

Thanks,
Reza

**Comment by bdionne** [comment] 2017-02-15 11:21
This seems like a separate issue. Do those qualifiers come up in the dialog box when you manually add a definition? Are the defaults that come up in the dialog your user login and current date?

It sounds like this is a separate issue.

**Comment by rmehri** [comment] 2017-02-15 14:43
Hi Bob,
Yes they do.  The same behavior occurs in ALT_Definition as well.  I will create a ticket and add a video clip for more details. 

Thanks,
Reza

**Comment by rmehri** [comment] 2017-02-17 23:14
Hi Bob, 
I have retested this issue using the same good input file and received successful batch out put file.  But the qualifiers did not get into GUI automatically.  I also manually added definition and that worked fine.  Please see attached screen shot and batch files for more details.  

![adding definition failed](https://cloud.githubusercontent.com/assets/8367102/23086654/4ef1fbea-f53c-11e6-86b5-15e6e9356754.png)
[RMv6-Def-Quals3-Good-Out.txt](https://github.com/NCIEVS/nci-protege5/files/784541/RMv6-Def-Quals3-Good-Out.txt)
[RMv6-Def-Quals3-Good.txt](https://github.com/NCIEVS/nci-protege5/files/784542/RMv6-Def-Quals3-Good.txt)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-02-18 00:44
Interesting, I just ran your input file, changing only the class id to something in my ontology, and it seemed to work fine. Let's do a screen share on Monday and see what's happening on your machine. I suspect that perhaps your ontology doesn't have the `required` property qualifier set?

<img width="1018" alt="screen shot 2017-02-17 at 7 40 19 pm" src="https://cloud.githubusercontent.com/assets/31741/23088280/0d38f1ec-f549-11e6-95ad-a9cbf4707d28.png">

**Comment by rmehri** [comment] 2017-02-21 19:43
Hi, 
This fix has been retested and verified using tag-123, editab-0.4.6. Please see attached input and output files for more details.

[Uploading RMv6-Def-Quals3-Good.txt…]()
[Uploading RMv6-Def-Quals3-Good-out.txt…]()

Thanks,
Reza

**Closed by rmehri** 2017-02-21 19:43 UTC
Labels: enhancement, fixed
