### ISSUE TITLE
Tag-106 -Build -Java Errors.

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#95] opened 2016-11-29 04:19 UTC
Hi, 
During building the protégé tag-106 on my machine, I have noticed a few java errors today. Despite that I can successfully launch the server and client on my workstation.  Please see the errors below and attached log file for more details. 

warning(24):  template error: context [/outputFile /parser /genericParser /region__/genericParser__members /region__/genericParser__members] 32:3 no such property or can't access: org.antlr.tool.Grammar.indirectDelegates
Caused by: org.stringtemplate.v4.misc.STNoSuchPropertyException: no such property: org.antlr.tool.Grammar.indirectDelegates
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.throwNoSuchProperty(ObjectModelAdaptor.java:106)
        at org.stringtemplate.v4.misc.ObjectModelAdaptor.lookupMethod(ObjectModelAdaptor.java:99)
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.ArrayList.removeAll(ArrayList.java:689)
        at org.antlr.tool.CompositeGrammar.getIndirectDelegates(CompositeGrammar.java:226)
        at org.antlr.tool.Grammar.getIndirectDelegates(Grammar.java:2722)

Regards,
Reza
[Build_Log 106.txt](https://github.com/NCIEVS/nci-protege5/files/618096/Build_Log.106.txt)

**Comment by NCIEVS** [comment] 2016-11-29 13:09
This is a duplicate of [#35](https://github.com/NCIEVS/nci-protege5/issues/35).  Closed as dup.

**Closed by NCIEVS** 2016-11-29 13:09 UTC
Labels: duplicate
