### ISSUE TITLE
Merges not always behaving

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#301] opened 2017-06-16 20:41 UTC
Workflow user should see merged class go under `Premerged_Concepts`

Merges did not go into the Premerged_Concept bin and went straight into the 
Retired_Concepts_Current_Year bin as if user had WorkFlow Manager privileges. (Note: I checked, 
user has been correctly assigned WorkFlow Modeler privileges and Al did a merge today that is in 
the Premerged_Concept bin as expected.)

 User was merging primitive children into defined parent concepts. This lead to the survivors of 
each merge having themselves as a primitive parent. Luckily, Pellet didn’t choke on these potential
cycles and it correctly inferred that these assertions were not needed (they weren’t being 
recognized as inferred superclasses) but having a merge lead to the assertion that the surviving 
class is its superclass is an unwanted behavior. Additionally, if this wasn’t a child being merged into
a parent but any primitive class being merged into a defined class, having the parent of the retired
class stay primitive in the defined surviving concept is not the behavior we would want. Fixing this 
second behavior may take some doing there will need to be some discussion establishing all of the
possible scenarios and desired behaviors first.

**Comment by bdionne** [comment] 2017-07-05 21:11
From [NS]:
"I just merged lung mucinous cystadenocarcinoma to its parent lung colloid carcinoma. I am doing some WHO-updating of lung cancers today. I followed the merge rules but, after I saved this merging action, the concept that was to be dropped, had disappeared from the terminology and I found it to be already retired instead of being in the premerged concepts. A similar thing had happened about 10 days ago and I had mentioned it to you as well."

It seems that under some circumstances the "save to premerge" is bypassed. We need more info at this time from [NS], but we'll have to prevent this bypass from happening.

**Comment by rmehri** [comment] 2017-07-12 22:32
Hi, 
Based on subject description and my understanding, I have retested using nci-1.007, NCI-Edit Tab 0.6.5, 
using workflow-modeler user. The problem exists.  Please see the testing steps below:

1)	Launch protégé client and server 
2)	Log into the protégé using Workflow-Modeler
3)	Select NCI Edit Tab
4)	Select a sub class 
5)	Select Edit/Convert primitive class and save it
6)	Select a parent class
7)	Select Edit/Convert to defined class and save it
8)	Select Complex Edit tab
9)	Select Merge radio button
10)	Drag primitive sub class to Retiring Concept pane.
11)	Drag defined parent class to Surviving concept pane.
12)	Save it 
13)	Go to Pre-merged Concepts bin and you’ll see the retired primitive subclass exists.
14)	You’ll see the Surviving Concept becomes the super class 
15)	Based on subject description, step14 is unwanted behavior. 
16)	Log out from protégé client.
17)	Log back into the protégé client using workflow-manager
18)	Select pre-merged class and complete the merge.
19)	Go to Retired Concept bin then you’ll see the retired primitive sub class
Please see attached snapshots for more details and let me know if you need more information.



![pre-merge1](https://user-images.githubusercontent.com/8367102/28142655-df072a42-672f-11e7-9a99-7ef54c444db7.png)
![pre-merge2](https://user-images.githubusercontent.com/8367102/28142650-df0088d6-672f-11e7-82c3-abbed33b7b98.png)
![pre-merge3](https://user-images.githubusercontent.com/8367102/28142651-df0352d2-672f-11e7-8c54-2a31351c1891.png)
![pre-merge4](https://user-images.githubusercontent.com/8367102/28142649-df0079b8-672f-11e7-8966-0c0934cde9a8.png)
![pre-merge5](https://user-images.githubusercontent.com/8367102/28142647-defd9eaa-672f-11e7-84e9-86dcfab34d77.png)
![pre-merge6](https://user-images.githubusercontent.com/8367102/28142652-df049f48-672f-11e7-82b9-928e979608f9.png)
![pre-merge7](https://user-images.githubusercontent.com/8367102/28142653-df065540-672f-11e7-812d-e726ddba08d6.png)
![pre-merge8](https://user-images.githubusercontent.com/8367102/28142654-df076444-672f-11e7-96d3-e53290a7e5ee.png)
![pre-merge9](https://user-images.githubusercontent.com/8367102/28142648-defe0a02-672f-11e7-835d-149c33e26596.png)
Thanks,
Reza

**Comment by bdionne** [comment] 2017-07-12 23:14
Thanks Reza,

This is not quite right, I tried this exact scenario you enumerate above and the merge looks ok, except that I'm not sure if it makes sense from a logical viewpoint.

The reported problem is that when a workflow modeler does a merge, the merged class goes right away to the retired tree, without the manager first completing it.

It happens in cases where a `primitive` class is merged into one of it's own `defined` parents. 

It's hard for me to read those screenshots but from your steps it looks like you are merging a primitive class into some other defined parent , which itself could also be problematic, but it's not the case at hand.

Best,

Bob

**Comment by rmehri** [comment] 2017-07-13 13:00
You're welcome! I will retest the scenario below and find out.
Bab stated:
It happens in cases where a  primitive  class is merged into one of it's own  defined  parents.
Thanks for your feedback,
Reza

**Comment by rmehri** [comment] 2017-07-13 15:19
Hi Bob,
I have retested using nci-1.007, NCI-Edit Tab 0.6.5, using workflow-modeler user. I could not reproduce it. It is working. Please see attached screen shot for more details.
![issue-301](https://user-images.githubusercontent.com/8367102/28173632-09c8df22-67bd-11e7-8ceb-29439406a387.png)

Thanks,
Reza

**Comment by NCIEVS** [comment] 2018-01-23 21:16
Don't know why this wasn't closed before after the QA was done.

**Closed** 2018-01-23 21:15 UTC
Labels: fixed
