### ISSUE TITLE
Edit rules not enforced

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#330] opened 2017-09-27 16:04 UTC
Users are able to put tabs and newlines into property values, which is against the [rules](https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege).

This caused bad data to get into `EVS` history, (see #328 )

**Comment by bdionne** [comment] 2017-10-31 15:50
The original issue is fixed in V2.1.010-DEV, but there are reports of other issues still.

**Comment by kondareddys2** [comment] 2017-12-01 16:14
Definition and ALT_Definition properties accept newlines and tabs and special characters.Attaching the image from QA server for version V2.1.012-DEV.


![definition and alt_defeination properties with newlines and tabs and special characters](https://user-images.githubusercontent.com/26006929/33491543-9864c2ac-d688-11e7-9525-5dbf837964e7.PNG)

**Comment by kondareddys2** [comment] 2017-12-01 17:24
Definition and ALT_Definition properties accept newlines and tabs and special characters.Attaching the image from QA server for version V2.1.012-DEV.
![definition and alt_defeination properties with newlines and tabs and special characters](https://user-images.githubusercontent.com/26006929/33494919-9eb859d4-d692-11e7-878b-2469e3c22e0b.PNG)

**Comment by singhik** [comment] 2018-02-16 21:24
Adding Complex properties to a Class  still accepts special characters, Tab and New line for  'DEFINITION','ALT_DEFINITION' and 'FULL_SYN' , hence retest failed ..

![image](https://user-images.githubusercontent.com/36314371/36329950-d5dbb160-1335-11e8-9dd2-4059ea2e8c74.png)

**Comment by bdionne** [comment] 2018-02-17 15:52
I don't think the special char rule applies of `DEFINITION`, only to `FULL_SYN`. For the others all the bas UTF8 chars are mapped to something else using this mapping [table](https://github.com/NCIEVS/nci-edit-tab/blob/master/src/main/resources/symbolmap.data)

The screenshots below show the warning you see when tabs and special chars are present in `FULL_SYN`. Please enumerate the steps you see that creates a fail.

Perhaps we should go over these [editing rules](https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege) with @NCIEVS 

<img width="1019" alt="screen shot 2018-02-17 at 10 46 15 am" src="https://user-images.githubusercontent.com/31741/36342689-d43b445c-13cf-11e8-843c-0cf29cbe0393.png">

<img width="1022" alt="screen shot 2018-02-17 at 10 46 46 am" src="https://user-images.githubusercontent.com/31741/36342692-e691b7da-13cf-11e8-93b4-1354d533e4fa.png">

**Comment by singhik** [comment] 2018-02-20 15:16
Hi,
    Please find below the steps 
1. Naviagte to 'NCI Edit Tab' in Protege client V2.2.0
2. Select any class from the Tree hiearchy and navigate to 'Edit' tab .
3. Click on + button for adding a complex property of type FULL_SYN.
4. Enter Preferred name with special characters and select a Term Type and Term Source .
5. Click 'OK' and then click on 'Save' .
Expected : Property (FULL_SYN) should not accept properties with special characters and throw a warning error .
Actual : Property (FULL_SYN) is accepting properties with special characters and getting them added .
Pfb, the screen prints of before and after addition : 

Before : 
![image](https://user-images.githubusercontent.com/36314371/36431916-dd12d186-1626-11e8-98b1-004fdf9c60e1.png)

After : 

![image](https://user-images.githubusercontent.com/36314371/36431983-070902da-1627-11e8-8ae4-0fe0f8120475.png)

![image](https://user-images.githubusercontent.com/36314371/36431994-102644e0-1627-11e8-9cc5-7b96cd29ec17.png)

**Comment by NCIEVS** [comment] 2018-02-20 15:26
Ah yes, we had slightly different rules for full_syns, definitions, and others.  Now with the character map, we might want to revisit & maybe make all the rules the same.

**Comment by bdionne** [comment] 2018-02-20 15:34
yea my understanding is that for `FULL_SYN` we check for "!", "?", "\t", and "\n" and for everything else we run it thru the character mapping table, which specifies what to transform other special characters to?

**Comment by bdionne** [comment] 2018-02-20 19:18
We need to review the requirements again on this one

**Comment by NCIEVS** [comment] 2018-02-20 20:31
have updated the wiki to clarify the special character rules, at https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege

**Comment by bdionne** [comment] 2018-02-22 19:29
Fixed in 2.2.0-beta2

**Comment by singhik** [comment] 2018-02-23 21:32
@bdionne : Hi, Unable to re-test on 2.2.0-beta 2  due to missing plugin jar in Edit Tab ..

**Comment by bdionne** [comment] 2018-02-23 21:56
@singhik - it's there now

**Comment by singhik** [comment] 2018-02-27 16:14
@bdionne  : Hi Bob, Complex Properties (DEFINITION,ALT_DEFINITION and FULL_SYN)   are accepting 'Greek charaters' and 'Special characters' In #,$,%,^,*,( . Pfb, the screen prints : 

![image](https://user-images.githubusercontent.com/36314371/36740034-54c5d308-1baf-11e8-8058-47b6cacd6382.png)

**Comment by bdionne** [comment] 2018-03-01 14:12
@singhik - actually I think this is ok, well at least it's accurately implementing the spec. If you look at the new [rules](https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege) it states that greek letters will be handled by policy, we don't check for those.

What we do check for is:

 * FULL_SYNs can't contain "!" or "?" but DEFINITION can

 * no chars less than ascii 32 (currently set to 25, I'll fix that). These are the control chars like tab newline and carriage return

 * all values are transformed using the [symbol mapping](https://github.com/bdionne/nci-edit-tab/blob/master/src/main/resources/symbolMap.data) data we were given

So I think the examples you tried are all acceptable. That said, I'm not so sure that's exactly correct. I discussed this with @NCIEVS (Gilberto) and he mentioned what we will do is add to that symbol data if needed

**Comment by singhik** [comment] 2018-03-01 16:37
@NCIEVS : Hi Gilberto , QA has verified below steps and the corresponding results for special chars rule . Please confirm on the coverage and correctness of the Expected Results per below : 

1. 'Greek characters' and 'Special characters'  @, #,$,%,^,*,(  are allowed in complex properties of FULL_SYN,ALT_DEFINITION,DEFINITION.

2. ALT_DEFINITION and DEFINITION complex property accepts ! and ?

3. FULL_SYN complex property does not accept ! and ? 

4. ALT_DEFINITION ,FULL_SYN and DEFINITION  do not accept Tab and NewLine control characters.

**Comment by NCIEVS** [comment] 2018-03-02 08:47
Yes, this is correct.  Any special characters that we wish to restrict in the future we’ll do so via the character map.

**Comment by bdionne** [comment] 2018-03-02 13:36
@singhik - on item 4. in your list, it's also other control characters. It's actually any character whose [ascii](http://www.asciitable.com/) code is less than 32.

In the `0.7.8` edittab push I made to fix the other issue, I also made a small [change](http://www.asciitable.com/) to this edit rule. I had been using ascii 25 instead of 32.

**Comment by singhik** [comment] 2018-03-02 18:33
Hi All,
          Post change of ASCII 25 to ASCII 32, QA has re-executed below steps and actual results ::
 1.  'Greek characters' and 'Special characters' @, #,$,%,^,*,( are allowed in complex properties of FULL_SYN,ALT_DEFINITION,DEFINITION.
  2.  ALT_DEFINITION and DEFINITION complex property accepts ! and ?
  3.  FULL_SYN complex property does not accept ! and ?
  4.  ALT_DEFINITION ,FULL_SYN and DEFINITION do not accept Tab and NewLine control characters.

This is in agreement with coverage and Expected Results as confirmed above hence closing this ticket

**Closed by singhik** 2018-03-02 18:33 UTC
Labels: Retest failed, bug, needs investigation, question, ready for QA
