### ISSUE TITLE
P5-Tag-109-Complex Properties-Tables Names Not Uppercase

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#109] opened 2016-12-05 23:24 UTC
There are combination of lower case and uppercase tables names in the complex properties . 
Please see attached snapshot for details. 
Thanks,
Reza

![complex properties_uppercase](https://cloud.githubusercontent.com/assets/8367102/20906797/fcf4c416-bb17-11e6-922e-d828b5d0bd44.png)

**Comment by bdionne** [comment] 2016-12-05 23:41
Not sure what the issue is? The column labels come from the `rdfs:label` on the annotation, it you edit those you can change the case

**Comment by NCIEVS** [comment] 2016-12-05 23:47
The workflow manager can edit the rdfs:label as desired.  closing ticket.

**Closed by NCIEVS** 2016-12-05 23:47 UTC
Labels: wontfix
