### ISSUE TITLE
validate utf-8 input in batch edit and batch load files

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#376] opened 2018-04-10 20:46 UTC
If a record has invalid characters (non-utf-8), output error message with record description, skip the record, and continue processing the rest of the records.

**Comment by NCIEVS** [comment] 2018-05-07 16:34
Here's a recent set of batch files with non-utf8 characters.
[non-utf8-batch.zip](https://github.com/NCIEVS/nci-protege5/files/1980642/non-utf8-batch.zip)

**Comment by singhik** [comment] 2018-05-21 15:33
@bdionne @NCIEVS :: Hello, I tried Batch Load with few Non UTF 8 Characters and i see they got uploaded and concept created successfully ? Please find below the screen prints :: 

Concept got created with Non-UTF-8 character ç  
![image](https://user-images.githubusercontent.com/36314371/40315876-9a281cfe-5cea-11e8-8f75-1f4e7753d868.png)

Concept got created with Non-UTF-8 character ñ 
![image](https://user-images.githubusercontent.com/36314371/40315894-ae9b7e24-5cea-11e8-9867-980896db59bc.png)


Concept got created with Non-UTF-8 character é

![image](https://user-images.githubusercontent.com/36314371/40315911-bfbf410e-5cea-11e8-8a24-120160695990.png)

**Comment by bdionne** [comment] 2018-05-21 16:07
@singhik - could you upload the input file you used to test this, I'll run it locally and see what the issue is

**Comment by singhik** [comment] 2018-05-21 16:10
Hi Bob, please find attached the load file i used ....The first three rows have Non-UTF-8 chars .

[Load_Itendra_Non_UTF_8.txt](https://github.com/NCIEVS/nci-protege5/files/2023245/Load_Itendra_Non_UTF_8.txt)

**Comment by bdionne** [comment] 2018-05-21 16:39
@singhik - the first 3 records look fine, I don't see ant non-utf8 in there

the 4th record has an extra tab, which causes an error. I think using '/t' as the delimiter makes it awkward, but I think that's what the modelers are used to.

the 5th record is valid utf8 but contains '!' which violates the edit rules

<img width="1020" alt="screen shot 2018-05-21 at 12 38 28 pm" src="https://user-images.githubusercontent.com/31741/40318815-f1283436-5cf3-11e8-9a00-987747007943.png">

**Comment by singhik** [comment] 2018-05-21 16:57
@bdionne : Hi Bob, i took the non UTF-8 chars from wiki, per below and it mentioned ç,é , ñ as non UTF-8. 

![image](https://user-images.githubusercontent.com/36314371/40319537-7563162e-5cf6-11e8-920f-e022b18edc5b.png)

**Comment by bdionne** [comment] 2018-05-21 17:14
not sure what to make of this, that file loads fine in emacs, and the editor with Eclipse. I don't see any instance of the replacement chars that we would see if there were non-utf8 chars.

Do you have the url for this wiki page?

**Comment by singhik** [comment] 2018-05-21 17:17
Hi Bob, yes, this is the URL : http://docwiki.cisco.com/wiki/Non-UTF-8_characters_needed_for_some_languages 

If you have a subset of Non-UTF-8, please do share, i can use them too .

**Comment by bdionne** [comment] 2018-05-21 17:28
attached is a file I got from the modelers, that I used for testing this, it has some non-utf8 chars in it. I don't know which specifically buy you can see them in most editors as they appear as a black diamond with a question make inside. That's a replacement char

[NCI CDISC gloss definitions.txt](https://github.com/NCIEVS/nci-protege5/files/2023491/NCI.CDISC.gloss.definitions.txt)

**Comment by singhik** [comment] 2018-05-21 18:34
Hi Bob, I used �  as a Non UTF 8 Char example , Load and Edit works with skipping the Non UTF 8 char record and processing the rest as Expected . Attached is the screen print document .

[Issue 376.docx](https://github.com/NCIEVS/nci-protege5/files/2023674/Issue.376.docx)

**Comment by bdionne** [comment] 2018-05-21 20:56
great, we can ask @NCIEVS about these other chars you used

**Comment by NCIEVS** [comment] 2018-05-22 00:17
I took a look at the file and the characters were utf-8:

   ef bb bf
ç   c3 a7
é   c3 a9
ñ   c3 b1

e.g. the accented e is encoded as hex c3 a9 (the first sequence is a byte order mark encoded in utf-8).  

My first suspicion was that the page itself from that wiki was encoded in utf-8, and that's the case.  Here's the charset attribute of the meta element in that page:

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

**Comment by bdionne** [comment] 2018-05-22 10:01
@NCIEVS  - Hi, yes, the input file also contains valid utf-8 chars. My question was whether you wanted to allow those or treat them as special as we do some of the others.

**Comment by NCIEVS** [comment] 2018-05-23 09:54
Oh, I misread the question.  OK, those characters should be allowed through; we'd add them to the replacement map if the editors request it in the future.

**Comment by singhik** [comment] 2018-05-29 18:29
@NCIEVS : Hi Gilberto, can we close this ticket ? I have verified one of the Non-UTF 8 chars (�)  and it skipped that record with exception and continued to the rest, both via Batch Edit and Manual Edit  ....

**Comment by NCIEVS** [comment] 2018-05-29 18:53
Hi Itendra, can you test with this file?  https://github.com/NCIEVS/nci-protege5/files/1980642/non-utf8-batch.zip.

**Comment by singhik** [comment] 2018-05-29 19:37
@NCIEVS : Hi Gilberto, I had tested those 3 files for Batch Edit Complex Property : 
>All of them did Skip Non UTF 8 characters at multiple lines .
>Other records were Processed as well but as i do not have the Set up (pre existing data) as editors, rest all records for me were processed as 'Already Exists' or 'Not Found',  which is Expected . 

I have attached the detailed screen print document with Output files as well for reference . I think we can close this ticket now ...

[Issue 376.docx](https://github.com/NCIEVS/nci-protege5/files/2050433/Issue.376.docx)

**Comment by NCIEVS** [comment] 2018-05-29 19:46
Sounds good.  Thanks!

**Closed** 2018-05-29 19:56 UTC
Labels: enhancement, pass, ready for QA
