### ISSUE TITLE
Unable To Save Concepts From Primitive To Defined  - Stage - Not Reproducible 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#467] opened 2020-08-11 22:27 UTC
From Garrett ::  3.4.0-qa2 Stage Build

• Which operation failed? (such as Merge, Copy, Creation, PT 
changing) Lost the save button 
Converting primitive to Defined 

• Approximately what time did this failure occur? 
12:00EDT 

• Description or sequence of steps followed: 
Editing existing concept. Added second parent, modified definition, converted from primitive to defined. 

• Concepts involved: 
C1000019 ‘Peezing’

• If necessary, please include the state that the concepts were in at the time of the incident (e.g. edits of roles, defined/primitive changes). Screenshot is good if possible.
Undefined (primitive) 

• Outcome (screen frozen, concept not created, had to log out and in to get things to work better): 
Save buttoned greyed out when changing primitive to defined. 

[Logs.log](https://github.com/NCIEVS/nci-protege5/files/5059758/Logs.log)

![image](https://user-images.githubusercontent.com/36314371/89955059-35444a00-dc00-11ea-880b-139552cd1194.png)

**Comment by singhik** [comment] 2020-08-11 22:27
This issue is not reproducible in Stage and QA for 3.4.0-qa2 Build ...

**Comment by bdionne** [comment] 2020-08-11 22:45
I think this is a duplicate of #450

**Closed** 2020-10-07 00:29 UTC
Labels: duplicate, pass
