### ISSUE TITLE
make properties that are restricted_by editable in batch only by editors in that editing group

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#377] opened 2018-04-10 20:50 UTC
E.g. if a DEFINITION (which can be restricted_by in its declaration) has the restriction asserted on it, e.g. Def_Curator=some_group, only people within some_group should be able to edit the property in batch (as well as in the GUI).

**Comment by singhik** [comment] 2018-05-18 19:43
@NCIEVS @bdionne :  Hello, I have followed similar steps to reproduce this but users **not** part of restriction groups are allowed  to add/edit/delete DEFINITION complex property .Please review and align on the steps if they are missing something else this is not as Expected :: 

[Issue 377.docx](https://github.com/NCIEVS/nci-protege5/files/2018394/Issue.377.docx)

**Comment by bdionne** [comment] 2018-05-18 21:58
@singhik - maybe we can do a screen share on Monday and review this. I looked at your screenshots and it looks like what you have done is correct. There was a an issue before where the user name was used rather than id, but that was fixed. I'll try to recreate your scenario and see if that exposes the bug here

**Comment by NCIEVS** [comment] 2018-05-18 22:04
Not sure if this might be it, but see if -enum (as opposed to _enum) in the datatype name does the trick.

**Comment by singhik** [comment] 2018-05-21 20:43
@NCIEVS : Hi Gilberto, Tried with -enum but does not seem to work, below are relative screen prints ::

DEFINITION associated with restriced_by property ::

![image](https://user-images.githubusercontent.com/36314371/40328734-6aeb92e2-5d15-11e8-9d15-38da7a1ce173.png)

Def_Curator  has a Range associated with Def_Curator-enum :: 

![image](https://user-images.githubusercontent.com/36314371/40328775-85dcbac2-5d15-11e8-8e1e-f9221c36ff43.png)

Def_Curator-enum  as two Datatype Definitions ::

![image](https://user-images.githubusercontent.com/36314371/40328789-9bc2bd82-5d15-11e8-90ae-c7933371babf.png)


"textArea" Datatype definition has 'safran' user only associated :: 

![image](https://user-images.githubusercontent.com/36314371/40328854-c8d2df64-5d15-11e8-8af3-9003a3bc2614.png)


Adding a concept with 'Def_Curator' and linking "textArea" ::


![image](https://user-images.githubusercontent.com/36314371/40328907-e9389762-5d15-11e8-9798-bade2d717a19.png)


Trying to add a complex property with singhik as user, should **not** allow as singhik is not part of group  but able to add complex property DEFINITION ::

![image](https://user-images.githubusercontent.com/36314371/40328961-104b4566-5d16-11e8-8f8f-71504f2703bd.png)

**Comment by bdionne** [comment] 2018-05-21 21:06
@singhik - if you have it handy, attach the input file you are using and I'll try it here. I notice you are using the legacy `Def_Curator`, which should be ok. I tried that also here and it works fine.

**Comment by bdionne** [comment] 2018-05-22 15:04
yea, definitely, tomorrow is best for me if you can do a webex then I'm pretty free all day.

The idea in this ticket is to extend those restrictions to the batch edit process. In other words when you try to edit a `DEFINITION` or any complex prop that has the `restricted_by` you need to belong to whichever group is specified for that class.

But if it's not working for you manually it won't in batch edit either, so we'll have to see why on your machine and then maybe I can reproduce the problem on mine.

**Comment by singhik** [comment] 2018-05-23 17:41
@bdionne :: Hi Bob,  Thanks to your Midas touch, 'restricted_by'  property works fine in sense of allowing only those users to Add/Edit/Delete a DEFINITION Complex property which are added in 'Datatype Definitions'  and not allowing Add/Edit/Delete of a DEFINITION Complex property by any other user, both via Manual as well as Batch(EDIT COMPLEX PTY) ....

However, i tried all the operations via batch, to test the regression functionality , Delete works fine but i am not able to perform Add of a Complex property(DEFINITION) via batch, File used and error are attached. 

Concept where trying to add a Complex Pty via Batch ::

![image](https://user-images.githubusercontent.com/36314371/40441337-b90f90e8-5e8e-11e8-9e53-42d798cd5964.png)


Batch File ,used to perform New Complex DEFINITION addition ::
[Add_Complex_Pty_Batch_RestrictedBy.txt](https://github.com/NCIEVS/nci-protege5/files/2032176/Add_Complex_Pty_Batch_RestrictedBy.txt)


Error description :: 

java.lang.NullPointerException: lexicalValue cannot be null
        at org.semanticweb.owlapi.util.OWLAPIPreconditions.checkNotNull(OWLAPIPreconditions.java:98)
        at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLLiteral(OWLDataFactoryImpl.java:302)
        at gov.nih.nci.ui.NCIEditTab.addComplexAnnotationProperty(NCIEditTab.java:1940)
        at gov.nih.nci.utils.batch.ComplexPropProcessor.processData(ComplexPropProcessor.java:168)
        at gov.nih.nci.utils.batch.BatchEditTask.processTask(BatchEditTask.java:65)
        at gov.nih.nci.ui.dialog.TaskProgressDialog$BatchProc.run(TaskProgressDialog.java:226)

**Comment by bdionne** [comment] 2018-05-23 20:09
@singhik - well that exception doesn't look helpful, I should provide something more useful. Are you sure you have the correct attributes in the file?

`C152542	new	P97	TestingComplexBatchNewPty	P384	SEER	P383	DN`

In my local copy of Thesaurus, the only qualifier I have for `DEFINITION` is `def-source`, which in the by-code version is `P383`. It looks like `ALT_DEFINITION` has an additional one, `comment` which I'm guess is `P384`? Anyway, you can check by using the interactive dialog, whichever qualifiers show up in the dialog will be the ones you can use in the batch input, except `Definition_Reviewer_Name` and `Definition Review Date` which are set automatically

**Comment by singhik** [comment] 2018-05-23 20:20
@bdionne : Hi Bob, I used similar format in previous release for Adding a complex pty (Definition) , it worked then, please find below it's screen print :: 

Input File ::

![image](https://user-images.githubusercontent.com/36314371/40448948-05e7cf5a-5ea5-11e8-8740-1944467d825a.png)


Batch Edit Complex Pty :: 

![image](https://user-images.githubusercontent.com/36314371/40448963-1324dc94-5ea5-11e8-97b9-884329357319.png)

![image](https://user-images.githubusercontent.com/36314371/40448969-1b46caa4-5ea5-11e8-9bf4-54bd580e22dd.png)

![image](https://user-images.githubusercontent.com/36314371/40448975-2055821a-5ea5-11e8-8bf6-afbdb15a4969.png)


DEFINITION complex property got added ::

![image](https://user-images.githubusercontent.com/36314371/40448997-31d4760e-5ea5-11e8-94f6-586d9c4c2223.png)

**Comment by bdionne** [comment] 2018-05-23 21:41
not sure what to make of it. It seems to work ok for me but my content has different codes for those properties. I don't have `P383` and `P384`. Can you check that you do have the correct values? You may be using the same inputs that worked before but someone else may have changed your content on the server. @safrant can you send me the `server-configuration.json` that's being used on the QA tier?

**Comment by safrant** [comment] 2018-05-23 22:04
The server-configuration.json has the following
DEFINITION:
        "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97": [
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Definition_Review_Date",
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Definition_Reviewer_Name",
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P378",
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P381"

FULL-SYN
        "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90": [
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P385",
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P386",
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#term-group",
          "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#term-source"

The P383 and P384 are the correct codes for term-group and term-source, but we don't use them because of some hardcoding in the business rules.  Even if we did use them, they wouldn't be applicable to the DEFINITION property.

   

    <owl:AnnotationProperty rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#term-group">
        <NHC0>P383</NHC0>
        <P108>term-group</P108>
        <required rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</required>
        <rdfs:label>Term Type</rdfs:label>
        <rdfs:range rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#term-group-enum"/>
    </owl:AnnotationProperty>
    


    

    <owl:AnnotationProperty rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#term-source">
        <NHC0>P384</NHC0>
        <P108>term-source</P108>
        <required rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</required>
        <rdfs:label>Term Source</rdfs:label>
        <rdfs:range rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#term-source-enum"/>
    </owl:AnnotationProperty>

**Comment by singhik** [comment] 2018-05-24 16:28
@safrant : Thanks Tracy, the attached file works fine . 
@bdionne @NCIEVS : QA has verified this Issue and is closing it .Attached is the detailed screen print documented results .

[Issue 377.docx](https://github.com/NCIEVS/nci-protege5/files/2036261/Issue.377.docx)

**Closed by singhik** 2018-05-24 16:28 UTC
Labels: enhancement, ready for QA
