### ISSUE TITLE
batch load matching for duplicates needs to be tweaked.

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#284] opened 2017-05-11 20:53 UTC
The function in batch loads that tests for the presence of duplicate PTs appears to be flagging matches too liberally.  We need to tweak the matching and use the enclosed files (a batch load and the log file) as guides (the test would need to be done against the full NCIt).  

I'm flagging the ticket as a bug because batch loads are run very frequently, so we want to queue this one for a fix and deploy sooner rather than later.

[v2.SPL-Load.txt](https://github.com/NCIEVS/nci-protege5/files/994374/v2.SPL-Load.txt)
[v2.SPL-LoadO.txt](https://github.com/NCIEVS/nci-protege5/files/994375/v2.SPL-LoadO.txt)

**Comment by bdionne** [comment] 2017-05-11 21:02
this is likely an issue with spaces in the names, similar to what we had in batch edits

**Comment by NCIEVS** [comment] 2017-05-11 21:33
oh, the spaces sere on the batch loads.  i checked last week's chat.

**Comment by NCIEVS** [comment] 2017-05-11 23:11
Turned out that the plugin with the fix hadn't been deployed yet.  So nothing much to do here, except that 6 lines had issues:

Temperature 25 (+/-) 2 Degrees C and Relative Humidity 60% (+/-) 5%	C96146
Temperature 30 (+/-) 2 Degrees C and Relative Humidity 65% (+/-) 5%	C96146
Temperature 40 (+/-) 2 Degrees C and Relative Humidity 75% (+/-) 5%	C96146
Temperature 30 (+/-) 2 Degrees C and Relative Humidity 75% (+/-) 5%	C96147
Temperature 25 (+/-) 2 Degrees C and Relative Humidity 40% (+/-) 5%	C96147
Temperature 30 (+/-) 2 Degrees C and Relative Humidity 35% (+/-) 5%	C96147

however, the following similar lines did go in:

Temperature 5 (+/-) 3 Degrees C	C96146
Temperature -20 (+/-) 5 Degrees C	C96146
Temperature 40 (+/-) 2 Degrees C and Relative Humidity Not More Than 25%	C96147

Will need to check character encodings from the office just in case, but the lines above might need to be run through the debugger.

**Comment by bdionne** [comment] 2017-05-12 09:27
We use search in the batch loader to check for dups.

The issue with 6 that fail and the 3 that succeed is that all of the chars in `(+/-)` are part of the lucene query syntax. You can see the same exception that the batch loader gets by using those strings in lucene search panel with an exact match search over label.

The strings with two instance of `(+/-)` break the parser, and the strings with only one just fail to find any results. So the 3 records that succeed in the batch loader will not be indexed properly and will be unsearchable.

This will take some time to fix as we'll have to audit the lucene-search-tab for all the places where escaping the search string is needed

**Comment by bdionne** [comment] 2017-05-17 12:57
Fixed in `lucene-search-tab-1.0.4`

**Comment by rmehri** [comment] 2017-05-25 02:39
Hi, 
I have retested and received errors.  I used the following:
Used Batch Type=Load
1) Used this dictionary : QA -Only-Thesaurus-byCode  via https://nciws-d699-v.nci.nih.gov:9090, and received the errors. Please attached input and output files for more details.
[Uploading v2.SPL-Load_284_Used Load.txt…]()
[Uploading v2.SPL-Load_284-Out-Used Load.txt…]()
2) Used the dictionary byname. via http://localhost:8080
 Received errors as well: Please attached input and output files for more details.
[Uploading Issue_284_Load_LocalServer.txt…]()
[Uploading Issue_284_Load_LocalServer-out.txt…]()

*Note: Please let me know what dictionary has been used for this issue.

Thanks,
Reza

**Comment by bdionne** [comment] 2017-05-25 18:49
per our conversation, if you could post the input/output files I can take a peek

**Comment by rmehri** [comment] 2017-05-25 18:52
Hi Bob,
Please see attached input and output files.  I retested them again.  I received exceptions for all except one record that already exists. 
1.Used this dictionary : QA -Only-Thesaurus-byCode via https://nciws-d699-v.nci.nih.gov:9090, 

[v2.SPL-Load-Input.txt](https://github.com/NCIEVS/nci-protege5/files/1029916/v2.SPL-Load-Input.txt)
[v2.SPL-Load-output-1.txt](https://github.com/NCIEVS/nci-protege5/files/1029918/v2.SPL-Load-output-1.txt)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-05-25 19:23
I looked at this input with `whitespace-mode` turned on and I can't see anything wrong.

I tried the exact same file, changing the codes for the parents to make it work against my content and it also works fine.

I have no idea what the problem is, you may want to test with some smaller input files and see if you can reproduce the error

**Comment by rmehri** [comment] 2017-05-25 22:22
Hi Bob, 
Thanks for your feed back!  I have updated the input file and retested this issue then  received the same errors. I will retry it on my local server and see if I receive the same errors. I am using the following dictionary:
"QA-Only-Thesaurus-byCode-161212" on https://nciws-d699-v.nci.nih.gov:9090.
Would please let me know what dictionary and environment did you test?
Thanks,
Reza

**Comment by bdionne** [comment] 2017-05-26 09:42
I tried it with both SmallBase.owl and Thesaurus-byCode-Template.owl, which is almost the full thesaurus, about 450M. Both worked fine for me.

I used your input file, suitably modified for my content, changed the code of the parent to match. One thing you might check is if the gencode file of your server is set properly, perhaps the codes generated for the new classes already exist.
<img width="1026" alt="screen shot 2017-05-26 at 5 37 22 am" src="https://cloud.githubusercontent.com/assets/31741/26489637/29384e0e-41d6-11e7-9560-f1fec1207fb5.png">

**Comment by rmehri** [comment] 2017-05-26 18:49
Hi, 
Thanks for your feedback! Per our conversation, I had an issue with the protégé on my local server. Thereby,  I have rebuilt and reconfigured it, then updated the input batch file and ran it successfully.  Please see attached snapshot and input and output batch files for more details.
May 26, 2017

Creating:	Commercial Batch	C1000001	C26548
Creating:	Development Batch	C1000002	C26548
Creating:	Clinical Batch	C1000003	C26548
Creating:	Validation Batch	C1000004	C26548
Creating:	Bioequivalence Batch	C1000005	C26548
Creating:	Experimentally Determined Chemical Structure	C1000006	C16612
Creating:	MDL Structure-data File	C1000007	C16612
Creating:	MDL Molfile	C1000008	C16612
Creating:	macromolecular CIF	C1000009	C81879
Creating:	Does Not Conform	C1000010	C81879
Creating:	Inverted	C1000011	C71018
Creating:	Valve-up	C1000012	C71018
Creating:	Valve-down	C1000013	C71018
Creating:	Drug Product Specification	C1000014	C90332
Creating:	Drug Substance Specification	C1000015	C90332
Creating:	Raw Materials/Excipients/Intermediates/Reagents Specification	C1000016	C90332
Creating:	Temperature 25 (+/-) 2 Degrees C and Relative Humidity 60% (+/-) 5%	C1000017	C54306
Creating:	Temperature 30 (+/-) 2 Degrees C and Relative Humidity 65% (+/-) 5%	C1000018	C54306
Creating:	Temperature 40 (+/-) 2 Degrees C and Relative Humidity 75% (+/-) 5%	C1000019	C54306
Creating:	Temperature 5 (+/-) 3 Degrees C	C1000020	C54306
Creating:	Temperature -20 (+/-) 5 Degrees C	C1000021	C54306
record 22:  -- super class does not exist.
record 23:  -- super class does not exist.
record 24:  -- super class does not exist.
record 25:  -- super class does not exist.
Creating:	Standard Environmental Condition	C1000026	C81903
Creating:	Cycled-Simple Environmental Condition	C1000027	C81903
Total run time was: 3430 ms
Total successful completion: 23 out of: 27
[v2.SPL-Load-Reza.txt](https://github.com/NCIEVS/nci-protege5/files/1032746/v2.SPL-Load-Reza.txt)
[v2.SPL-Load-Reza-Output.txt](https://github.com/NCIEVS/nci-protege5/files/1032747/v2.SPL-Load-Reza-Output.txt)
![issue_284_1](https://cloud.githubusercontent.com/assets/8367102/26508350/6b96cb4e-4222-11e7-817e-67e7afc9db36.png)

Thanks,
Reza

**Closed by rmehri** 2017-05-26 18:49 UTC
Labels: bug, fixed
