### ISSUE TITLE
periodic issues with a disabled Save, and its effect on history

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#311] opened 2017-07-10 22:41 UTC
From [EHD]:
"I had trouble trying to Retire a concept. (Prothymosin L C1921) Someone else (I believe Cynthia) was editing and when I went to hit Save I kept getting a message that I needed to update my copy. Since I am a WorkflowManager, when I exited the warning box, the concept was in the Retired_Concept_Current_Year bin but when I went back to the Retire tab I didn’t have the option to Save (the Save and Cancel buttons were not available). So I logged out and logged in (the retire had not been committed); I attempted to complete the retire with the Auto-Update off but I got the same message and had the same result. So I had to save the uncommitted changes using the Server>Commit menu option. This saved the uncommitted changes but this may not be marked as a RETIRE because the Revision History is showing the “Commit Retire” message that I typed in and not RETIRE as the action for that set of edits."

"So there are two issues here, I is the unavailable Save button after updating the local copy and the other is the incorrect history record because it was a Commit instead of a Save."

**Comment by NCIEVS** [comment] 2017-07-10 22:42
Separately, this particular action will require that the history files be manually fixed on the ops side.

**Comment by bdionne** [comment] 2017-07-10 23:30
@rmehri - we need reproducible steps for this, if you have a chance.

@NCIEVS - should we consider disabling the commit menu item? We need it for when managers are editing annotation property definitions, but this is exactly the case we wanted to avoid.

A preferable option here would have been to use the history/undo menu item to back out the uncommitted changes.

**Comment by NCIEVS** [comment] 2017-07-11 21:55
Undo history sounds good.  Let's keep this ticket open but at a lower priority.  I'll go over Undo & Revision History with [EHD] and [NT].

**Comment by rmehri** [comment] 2017-07-12 18:14
Hi,
Based on the subject description and my understanding, I have retested this issue using nci-1.007, NCI-Edit Tab-0.6.5 , I could not reproduce this bug. Please see my retesting steps below:

1)	Launch protégé client and server 
2)	Log into the protégé using Workflow-Modeler
3)	Select NCI Edit Tab
4)	Select a class or concept
5)	Try to add definition to existing class 
6)	Do not save it 
7)	Launch another client and login to the protégé as Workflow-Manager
8)	Select NCI Edit Tab and locate the same class
9)	Right click on the same class and select retire 
10)	Try to save it
11)	The class gets retired without any error.
12)	Log out from protégé
13)	Log back into the protégé as Workflow-Manager
14)	Click Server
a)	The Commit is greyed out 
b)	There are no uncommitted changes 
15)	Select Revision History tab, then you’ll see the committed retired class.


![retire1](https://user-images.githubusercontent.com/8367102/28132752-c315eb1c-670b-11e7-98b0-2a6dee7e100d.png)
![retire2](https://user-images.githubusercontent.com/8367102/28132756-c31b413e-670b-11e7-85ca-a56bac44a693.png)
![retire3](https://user-images.githubusercontent.com/8367102/28132755-c317a11e-670b-11e7-9aa8-e7225e701614.png)
![retire4](https://user-images.githubusercontent.com/8367102/28132753-c316f0f2-670b-11e7-9fd6-de16bf0dadb7.png)
![retire5](https://user-images.githubusercontent.com/8367102/28132751-c315aad0-670b-11e7-9d66-e713dfd0b5ba.png)
![retire6](https://user-images.githubusercontent.com/8367102/28132754-c316ffca-670b-11e7-8238-d237dd598a3c.png)

Please see attached snapshots for more details and let me know if need more information.
Thanks,
Reza

**Comment by bdionne** [comment] 2017-07-12 20:43
Thanks Reza, I actually think I see how to reproduce this. I'll try a couple of things

**Comment by bdionne** [comment] 2017-07-13 13:05
Ok, I can reproduce this:

1. Bring up two users, one logged in as Alice, the other Bob (workflow modeler and manager)
2. Bob begins retiring a class, fixes up the usages, add the design/editor notes, and is ready to hit save, but *doesn't*
3. Alice does any edit, and saves
4. Bob hits save, and will see the error dialog that he needs to update. When he dismisses the dialog the save button is now disabled

I have a fix for this which is being tested. 

The correct behavior (after the fix) when the user sees this error about being out of date, it to either wait until the autoupdater brings the content up to date, or manually click `server/update` and bring it up to date, then hit save again.

**Comment by bdionne** [comment] 2017-07-13 13:29
[fixed in 0.6.6](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.6.6)

**Comment by rmehri** [comment] 2017-07-14 18:36
Hi, 
Thanks , I have retested this fix using the steps above and the latest tag nci-1.008, nci-edittab-0.6.6.  No errors were occurred.  Please see attached screen shots for more details.

![issue-311-manager](https://user-images.githubusercontent.com/8367102/28225770-c3a14fd0-68a1-11e7-9bb5-da1f777df227.png)
![issue-311-modeler](https://user-images.githubusercontent.com/8367102/28225775-c973106a-68a1-11e7-88ba-f3f4f702108b.png)

Thanks,
Reza

**Closed by rmehri** 2017-07-14 18:36 UTC
Labels: bug, fixed
