### ISSUE TITLE
Alice Login-Adding Complex Property -FULL_SYN Gets Duplicate 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#48] opened 2016-10-15 18:27 UTC
Steps to reproduce:

1) Log into the protégé as Alice http://localhost:8080 via "Open from Protégé OWL Server"
2) Open "foo" project 
3) Select a class
4) Add Complex property with value "FULL_SYN" 
5) Save it and you'll see it get created in the row, but it duplicated the FULL_SYN in upper section of page. 
Please see attached screen shots for more details.

Thanks,
Reza
![add complex propert_1_alice login](https://cloud.githubusercontent.com/assets/8367102/19412394/4a146876-92e3-11e6-8e04-b7f72992933e.png)
![add complex propert_full_syn_2_alice login](https://cloud.githubusercontent.com/assets/8367102/19412399/5b444e7c-92e3-11e6-95d9-be1dca79aca6.png)
![add complex propert_full_syn_3_alice login](https://cloud.githubusercontent.com/assets/8367102/19412402/6e1d368a-92e3-11e6-8310-9461269877a6.png)
![add complex propert_full_syn_4_alice login](https://cloud.githubusercontent.com/assets/8367102/19412405/7c8f09fa-92e3-11e6-84fe-d082c4aea442.png)

**Comment by bdionne** [comment] 2016-10-17 20:29
This is not a duplicate, the issue is the header is not resizing when there is only one table

**Comment by NCIEVS** [comment] 2016-11-29 18:30
Agreed, plus the header was conflated with the value.  Will close with invalid and wontfix.

**Closed by NCIEVS** 2016-11-29 18:30 UTC
Labels: invalid, wontfix
