### ISSUE TITLE
losing connectivity connectivity to server might impact state

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#421] opened 2019-06-25 19:30 UTC
On June 6, 2019 [AG] observed a very unstable protege.  The log showed multiple stackoverflow errors present in multiple sessions launched during this time period.  The first exception, however, was an unknownhost exception.  It might be possible that the instability was caused by this initial unknownhost exception; however, it's not clear how the instability may have persisted through multiple sessions.

Attached is an abbreviated log of this time period.  The first time a specific exception shows up in the log the first 10-30 lines of the stack trace is shown, thereafter only the two lines of the trace are shown along with the timestamped error message.  The blocks of the log specific to each session start with a "INFO  ProtegeApplication    ------------------------------------ Protege ----- . . . " message.

Perhaps these exceptions can be caught and handled more gracefully, especially the unknownhost.

[protege-2nd-day-abbrv.log](https://github.com/NCIEVS/nci-protege5/files/3369816/protege-2nd-day-abbrv.log)

**Comment by singhik** [comment] 2019-08-14 12:23
@NCIEVS : Hello, Does this Exception happens only when Server connection is lost ? If there are other reasons (known), please do let know so that i would simulate them all .

@bdionne : Hello, can you please share what was changed or added in the code to handle this Server Connectivity Exception ? Trying to derive Use Cases of this Scenario hence seeking any/all  information available as i am unable to reproduce it ....

**Comment by NCIEVS** [comment] 2019-08-14 15:28
Hi @singhik , I can't say for sure but the exception suggests that it can't find the DNS.  I think @bdionne  tested by disconnecting the wire or disabling networking, but can't recall whether this was enough to lead to the exception.

**Comment by bdionne** [comment] 2019-08-14 17:14
Hi @singhik , I'm not really sure of this one, as the description just says it was unstable without any detail of what if anything wasn't wrong. The exception you can reproduce by connecting to a host that doesn't exist.

The main change we made in the protege-server in this release is to force a [restart](https://github.com/NCIEVS/protege-server/commit/36372f473b3fdca7f8f0a6b06ec5669fccc99b01) after a squash occurs. The reason for the change is that we suspect the changesets were corrupted in the sequence numbers because the server's cache of them was out of sync and some modelers stayed logged in during and after a squash session.

For this ticket I tried killing the server when a client was already logged in, and after the server was brought back up, if I try to commit it just prompts the user to login again and then proceeds to commit, which is the expected behavior

**Comment by singhik** [comment] 2019-08-18 03:02
@bdionne :: Hello, I got an Exception thrown (Different than Client Server Exception as above) when i tried 'Disconnecting' and 'Reconnecting' a Server and unless restarted,Protege Client was not usable . Have attached a detailed document with steps used and Exception Logs.

[Issue 421.docx](https://github.com/NCIEVS/nci-protege5/files/3512665/Issue.421.docx)

**Comment by NCIEVS** [comment] 2019-08-19 14:40
Hi @singhik , I think this one might be different, more related to initialization of the nci edit tab than the loss of connectivity.  Perhaps disconnecting the wire of disabling networking might be closer to the loss in connectivity in the ticket?

**Comment by singhik** [comment] 2019-08-19 17:47
@NCIEVS : Hello, yes this Exception is different than above as i stated and is related to NCI TAB re-initialization . As far as disconnecting the network and reconnection goes, that Exception is handled fine post re-connectivity and Protégé comes back fine without having to restart .

Shall I close this ticket and open a new one for the Exception thrown when connection to Server is lost and NCI Edit Tab is throwing an Exception ?

**Comment by NCIEVS** [comment] 2019-08-19 17:55
@singhik :  yes, I think this one can be closed and a different one opened for tthe initialization.  You may want to search in the other tickets, we may have run into this one before and we may have concluded that it was a "won't fix" and closed it.  Can't recall right now.

**Comment by singhik** [comment] 2019-08-19 17:58
@NCIEVS :: Hello, Ok, Closing this ticket and will search GitHub for the old tickets for that Exception, else will raise a new one against 'Future Release' bucket.

**Closed by singhik** 2019-08-19 17:58 UTC
Labels: Retest failed, bug, medium priority, needs investigation, ready for QA
