### ISSUE TITLE
From UAT [EHD 2/27] - editing associations

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#210] opened 2017-03-03 21:24 UTC
When an editor chooses to add a Concept_In_Subset, the Add Annotations window should switch automatically to Entity IRI.

**Comment by NCIEVS** [comment] 2017-03-03 21:26
This might have been fixed already and might be a configuration issue.  

To restate:  any property whose range is xsd:anyURI in the declaration, when edited as an annotation on a class should come up with the  Entity IRI tree widget.

**Comment by bdionne** [comment] 2017-03-08 20:36
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment] 2017-03-15 22:28
Hi, 
I have retested this fix using tag-125, NCI Edit-0.5.0. 
1) Log into the local server (8080)
2) Select a class
2) Under General tab, and + sign to add annotation 
3) Select Type: xsd:anyURI
4) Select and add Concept_In_Subset
5) Window did not switch automatically to Entity IRI. (?)
6) Repeat step#1 through step#4 using "https://nciws-d699-v.nci.nih.gov:9090"
7) It switched in the  Entity IRI tab  with owl: Thing in Abstracting window (?)
Please see attached screen shots for more details.

![issue 210-1](https://cloud.githubusercontent.com/assets/8367102/23973496/d4715dd6-09ac-11e7-8f4d-331bda97cf80.png)
![issue 210-2](https://cloud.githubusercontent.com/assets/8367102/23973504/dfb6ae76-09ac-11e7-87de-d72f3ea5a436.png)
![issue 210-3](https://cloud.githubusercontent.com/assets/8367102/23973509/e3424622-09ac-11e7-848e-b10512867b9c.png)
![issue 210-1-dev server](https://cloud.githubusercontent.com/assets/8367102/23973516/eb7e71e4-09ac-11e7-84ff-03d6195ea6d0.png)
![issue 210-2-dev server](https://cloud.githubusercontent.com/assets/8367102/23973518/ed562b2e-09ac-11e7-813f-8b789b362c26.png)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-03-15 22:49
it's hard to tell from your screenshots, but it looks like the issue is that your content does not have the correct range for `Concept_In_Subset`. It's probably set to `xsd:string` and needs to be `xsd:anyURI`

**Comment by rmehri** [comment] 2017-03-16 14:36
Hi Bob,
Thanks for your feedback! Please see attached zip file to play the video clip for more clarification.  Also, we can discuss about this issue in our today's meeting as well. 

[Issue-210.zip](https://github.com/NCIEVS/nci-protege5/files/847996/Issue-210.zip)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-03-16 17:40
@rmehri - this 5 minute video shows basically the same thing as your screenshots and doesn't add any clarification. The question I have, which perhaps you can look into if you have time before we meet, is whether the range is correctly set for `Concept_In_Subset`. 

It seems that it is in one case but not the other. If you can verify that we can then determine whether this works as intended and is just a content configuration error as @NCIEVS mentions above, or is a bug we need to look into.

Please read my last comment and let me know if you have more questions.

**Comment by rmehri** [comment] 2017-03-16 23:10
Hi Bob, 
Thank you for your feedback! This fix has been retested and verified using tag-125, nci edit tab-0.5.0.  

Thanks,
Reza

**Closed by rmehri** 2017-03-16 23:10 UTC
Labels: current requirement, fixed
