### ISSUE TITLE
Tag-1.0068- Duplicated Project Name Cannot Be Removed,

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#298] opened 2017-06-13 19:27 UTC
Steps to reproduce:

Latest Tag: nci-1.0068
Edit Tab: 0.63
Metaproject Admin: 1.0

1) Log into to Admin Server as administrator "Bob"
2) Create project using ProdByCode template and SmallBaseByCode.owl and name the project ProdByCode 
3) Select JSON Serialization and save it as duplicated project  and no warning occurs 
4) At this point you don't see the duplicated project on server admin screen unless you logout and log back into the server admin then you see duplicated " ProdByCode.
5) I try to delete this new project ProdByCode and received an error 
Problems: 1) It should not accept duplicated project name.
                  2) When creating more than one project and save it the second or third project does not   display on admin server screen unless log out and log back in.

Please see attached log file and screen shots for more details.
[Server_Log file. txt.txt](https://github.com/NCIEVS/nci-protege5/files/1072615/Server_Log.file.txt.txt)

![prodbycode_duplicated name](https://user-images.githubusercontent.com/8367102/27100505-5b713136-504c-11e7-9a36-c05ae984518d.png)
![prodbycode_duplicated name1](https://user-images.githubusercontent.com/8367102/27100509-5e545d60-504c-11e7-9496-4a01d2634323.png)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-06-13 19:49
@rmehri - we need to triage this a bit before claiming a bug here.  Some clarifications:

It's not clear you created a duplicate, what was the first project you created?  If as in step 2. above you create a new project and use one of the template name as the name, you will in fact see a duplicate.

I suspect that what you did was try to delete the template, which doesn't have a history file. That would give you an exception, but should not affect anything.

Nothing prevents the admin user from creating a project with the same name, as the name is no longer connected to the project id.

<img width="1019" alt="screen shot 2017-06-13 at 3 43 17 pm" src="https://user-images.githubusercontent.com/31741/27101408-a3af1258-504f-11e7-8c1b-10e4b9293460.png">
<img width="1023" alt="screen shot 2017-06-13 at 3 43 32 pm" src="https://user-images.githubusercontent.com/31741/27101456-d188032e-504f-11e7-9e31-ef5edb5073bf.png">

<img width="1018" alt="screen shot 2017-06-13 at 3 43 42 pm" src="https://user-images.githubusercontent.com/31741/27101464-d785478c-504f-11e7-8af9-ef91fd5b8bb0.png">

**Comment by bdionne** [comment] 2017-06-13 20:40
@rmehri  - are you waiting long enough to see the new project show up? The only way I can reproduce the exception is if I tried to delete the template by mistake. As mentioned, it's harmless because for the template there is no underlying file to delete.

I think you are testing issue #252 ? If you review the scenario there, the user wants to create a new project that is a copy of another, and then rename it. That scenario works for me just fine. I'm not sure why you don't see the projects show up, does this happen on normal creates as well?


<img width="1020" alt="screen shot 2017-06-13 at 4 06 12 pm" src="https://user-images.githubusercontent.com/31741/27103546-042738de-5057-11e7-9bb0-1cdf431de32a.png">
<img width="1017" alt="screen shot 2017-06-13 at 4 06 26 pm" src="https://user-images.githubusercontent.com/31741/27103547-042b1062-5057-11e7-8cfc-bd364f882ea7.png">
<img width="1017" alt="screen shot 2017-06-13 at 4 07 11 pm" src="https://user-images.githubusercontent.com/31741/27103544-0424f8c6-5057-11e7-9fa9-f75ca0562cb0.png">
<img width="1018" alt="screen shot 2017-06-13 at 4 07 29 pm" src="https://user-images.githubusercontent.com/31741/27103545-042505d2-5057-11e7-8614-3322d136c047.png">
<img width="1016" alt="screen shot 2017-06-13 at 4 07 39 pm" src="https://user-images.githubusercontent.com/31741/27103543-0423c082-5057-11e7-86df-5a3902666c31.png">

**Comment by bdionne** [comment] 2017-06-16 19:38
Not sure about status of this, I thought this was #252 which was tested and closed, so I'm closing this for now. @rmehri if there's an issue here let's just comment on #252 unless we want to open a new ticket

**Closed by bdionne** 2017-06-16 19:38 UTC
Labels: cannot reproduce, needs investigation
