### ISSUE TITLE
Tag-126-System Administration-Adding New Users Not Showing in Server Admin Page

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#241] opened 2017-03-23 21:25 UTC
Steps to reproduce:
Used tag-126 
1.	Launch server and client
2.	Log into local host http://localhost:8081 ==>" Server Admin"
3.	Use "Bob"
4.	Select + to add new user 
5.	Press ok 
6.	Select JSON Serialization and save 
7.	You’ll notice that the created user does not show on page 
8.	Repeat steps 4 through 7 for multiple users and still the names do not show 
9.	Logout and log back into the server then you’ll see the created users ‘names. 
Please see attached snapshots for more details.

![server_admin_user creating](https://cloud.githubusercontent.com/assets/8367102/24270965/a1ae1672-0fed-11e7-9e91-2aa74068cfcb.png)
![server_admin_user creating-1](https://cloud.githubusercontent.com/assets/8367102/24270969/a71e87ea-0fed-11e7-8d7f-31a1eb4ac13c.png)

Thanks,
 Reza

**Comment by bdionne** [comment] 2017-03-23 21:33
@rmehri - I'm pretty sure this is a duplicate of #147 - which you reported some time ago. We speculate this is just a refresh issue, but minor and assigned the ticket to the next release

**Comment by bdionne** [comment] 2017-03-23 21:33
Please reopen if this is not a duplicate of #147

**Closed by bdionne** 2017-03-23 21:33 UTC
Labels: duplicate

**Comment by rmehri** [comment] 2017-03-24 13:31
Hi Bob,
Yes, you're correct. This is a duplicate of #147.
Thanks,
Reza
