### ISSUE TITLE
Save Button Disabled Post Concept Creation

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#539] opened 2022-01-11 20:55 UTC
@NCIEVS @bdionne  :  

Creating Concepts and trying to add complex properties, disable the 'Save' button, clicking on it does not invoke Concept Save func. 

![image](https://user-images.githubusercontent.com/36314371/149020097-e1fc8742-c4d1-42b3-82d5-7ef5a1b7ba8e.png)

**Comment by bdionne** [comment] 2022-01-11 21:13
@singhik Is this reproducible? Do you have a specific scenario? Based on your screenshot I tried the same thing and it works fine. I can see from the navigation panel that you have an edit in progress. Perhaps the save did execute but failed? Do you have any exceptions in the log or on the console?

We did find an issue with plugin versions, that's completely unrelated but you might try pulling the edit tab and curator plugins again. But first I'm interesting in whether you have a reproducible scenario


<img width="1016" alt="Screen Shot 2022-01-11 at 4 07 16 PM" src="https://user-images.githubusercontent.com/31741/149021637-de4a117d-9bfd-4301-9a8a-722efd27b009.png">

**Comment by singhik** [comment] 2022-01-11 21:28
@bdionne  : Scenario is as straight fwd as trying a concept creation and adding complex properties .
                     Yes, i see Exceptions, Logs.txt is attached .
[Logs.txt](https://github.com/NCIEVS/nci-protege5/files/7849943/Logs.txt)

I am working with these plugins as my final output for 3.9.0  : 
![image](https://user-images.githubusercontent.com/36314371/149024236-b751d179-d5de-459a-94bf-a0e35d5047f7.png)

**Comment by bdionne** [comment] 2022-01-11 21:40
@singhik Is it reproducible? If you restart and do the same test does it throw the same exception?

**Comment by singhik** [comment] 2022-01-11 21:52
@bdionne : No,it's not reproducible .

**Comment by bdionne** [comment] 2022-01-11 22:01
The exception is odd, it's indicating there's no active ontology, as if it's not fully logged in or the client has lost the ability to update.

**Comment by NCIEVS** [comment] 2022-01-18 17:40
Hi @singhik , when adding complex properties, did you save the concept first and then tried to add them?  Or did you try to add them to the newly-created concept right after creation?  

Also, which property were you trying to add on your first try?  Just wondering if this is a complex property that we have mis-configured (and once you got the exception there was no way of this working with another property) in the same session.

**Comment by NCIEVS** [comment] 2022-01-18 17:40
@bdionne @singhik PS I've moved this out of the 3.9.0 milestone.

**Comment by singhik** [comment] 2022-01-18 17:45
@NCIEVS : Hi, I added complex properties to a new concept during and after creation , i added alt-defs ....

**Comment by NCIEVS** [comment] 2022-01-18 17:57
@singhik , OK, I couldn't reproduce it either.  used alt-def for both during and after creation.

**Comment by bdionne** [comment] 2022-10-12 19:43
From the logs this looks like a bad config, ontology, active ontology, etc... closing this. Please re-open if there is a reproducible test case and/or it happens again

**Closed by bdionne** 2022-10-12 19:43 UTC
Labels: bug, needs steps to reproduce/triage, not reproducible
