### ISSUE TITLE
Right-click popup menu in tree widget is temperamental

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#221] opened 2017-03-03 21:50 UTC
The right click menu on the hierarchy is clunky and sometimes temperamental, often you need to change the focus and then refocus on your concept of interest for the right click menu items to be active. A button would also be more like what we have now for adding Annotations and SubclassOf. When someone creates a new concept, they will need to add a DEFINITION and you have to use the right click menu since there is no DEFINITION table yet. Having to Save, refocus the hierarchy, then return to your new concept takes time. A button that acts like the menu item could be a huge time saver. However, this probably can still wait for a Future Release.

[Adding a DEFINITION during class creation is something we want to do; the initial dialog that only has a text box for the PT would need to be modified.  Would suggest that the "def" property be identified in the metaproject, along the lines of the fully qualified syn.  Needs triaging, might really be a feature request for future release.]

**Comment by bdionne** [comment] 2017-03-04 11:46
This is pretty much the same as #58 There's really three issues here:

 * adding a button ( #58)
 * add definition to the add subclass dialog
 * temperamental popup on right click in the navigation pane

I took a closer look at the popup issue, and it's a deep issue in the protege code. You can see the identical behavior in the entities tab:

 * select a class in the classes pane
 * select a property in the annotations for that class
 * go back to the navigation pane and click right on the class to display popup
 * notice certain items are greyed out (this is because the class does not really have focus
 * click left on the same class, now click right again and see correct popup

**Comment by bdionne** [comment] 2017-03-08 20:32
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment] 2017-03-14 16:18
Hi Bob, 

Are the following part of this fix? 

This is pretty much the same as #58 There's really three issues here:
•adding a button ( #58)
•add definition to the add subclass dialog
•temperamental popup on right click in the navigation pane

Thanks,
Reza

**Comment by bdionne** [comment] 2017-03-15 15:03
No, see the labels on #58, that's for a future release. This fixes the flakiness in the right click popup, as described above.

**Comment by rmehri** [comment] 2017-03-15 15:58
Hi, 
Thanks, based on your feedback and status of this issue.  This is duplicated issue with #58.
Reza

**Comment by bdionne** [comment] 2017-03-15 16:03
@rmehri - actually this is a separate, the flakiness of the right popups. In fact, to repeat my comment above, this is very reproducible:

I took a closer look at the popup issue, and it's a deep issue in the protege code. You can see the identical behavior in the entities tab:
 * select a class in the classes pane
 * select a property in the annotations for that class
 * go back to the navigation pane and click right on the class to display popup
 * notice certain items are greyed out (this is because the class does not really have focus
 * click left on the same class, now click right again and see correct popup

**Comment by rmehri** [comment] 2017-03-15 20:42
Hi
I am not clear why the status of this ticket was set as "duplicate" and ready for QA previously and it is reopened now. Has this ticket been fixed? Or we should we wait for next the release? 

Thanks,
Reza

**Comment by bdionne** [comment] 2017-03-15 20:52
@rmehri - I reopened this (see my last comment above), *removed* the duplicate tag and marked it ready for QA because there is something this ticket speaks to, the flakiness of the right popup behavior, and that is fixed in this latest build. So it needs to be tested.

In my comment above I also enumerate the steps you can use to test this flakiness, if you've already confirmed that this is indeed fixed, then by all mean, you can close this ticket.

**Comment by rmehri** [comment] 2017-03-16 16:23
Hi, 
Thanks for your comment,  I have retested this issue using tag-125, NCI Edit Tab-0.5.0
Used: Modeler and Manager logins
Used the following servers:
https://nciws-d699-v.nci.nih.gov:9090
http://localhost:8080

1) Select a class in the classes pane
2) Select a property in the annotations for that class
3) Go back to the navigation pane and click right on the class to display popup
4) Notice certain items are greyed out (this is because the class does not really have focus .....> ( In Entities tab, the "Copy" link is greyed out) ?
5) Click left on the same class, now click right again and see correct popup --> ( In Entities tab, the "Copy" link is still showing greyed out) ?
Please see the attached screen shots for more details.
![entities-copy link greyed out](https://cloud.githubusercontent.com/assets/8367102/24006840/3d723436-0a43-11e7-92e0-046dabfd6cb3.png)
![entities-copy link greyed out1](https://cloud.githubusercontent.com/assets/8367102/24006852/45a46426-0a43-11e7-8bf8-4f6a7b60323b.png)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-03-16 17:36
You're welcome, this works for me, I'm not sure what the behavior is on Windows machines.

The important question is though, does it work in `EditTab`?

**Comment by rmehri** [comment] 2017-03-16 19:18
Hi Bob, 
I have used the following steps and replicated this issue for NCI Edit tab. 
Used: Modeler and Manager logins
 Used the following servers:
https://nciws-d699-v.nci.nih.gov:9090
http://localhost:8080

1.Select a class in the classes pane
2.Select a property in the annotations for that class 
3.Click right on a annotations property -------> (A few items are showing greyed out) 
4.Go back to the navigation pane and click right on the class to display popup .....> ( There was no greyed out item.) 
5.Click left on the same class, now click right again and see correct popup --> ( There was no greyed out item.) 
 Please see the attached screen shots for more details.

![nci edittab_greyed items](https://cloud.githubusercontent.com/assets/8367102/24014421/439923fc-0a5b-11e7-8e66-1b8761e2b667.png)
![nci edittab_greyed items-2](https://cloud.githubusercontent.com/assets/8367102/24014465/6baeeb10-0a5b-11e7-8479-e23680213656.png)

Thanks,
Reza

**Comment by bdionne** [comment] 2017-03-16 19:26
@rmehri - this is working fine as intended. Your steps to reproduce are not the same as those I outlined above. This has nothing to do with the popup behavior on the annotation properties, but rather the popup on classes in the navigation pane. 

I think if you run `nci-0.123` and follow the steps I outlined above you can see the bad behavior

**Comment by rmehri** [comment] 2017-03-16 23:09
Hi Bob, 
Thank you for your feedback and support! This fix has been retested and verified using tag-125, nci edit tab-0.5.0.  

Thanks,
Reza

**Closed by rmehri** 2017-03-16 23:09 UTC
Labels: bug, fixed
