### ISSUE TITLE
Cannot select dates in EVS History tab calendar

### ISSUE THREAD

**Issue by fragosog** [NCIEVS/nci-protege5#565] opened 2023-02-07 16:09 UTC
Either in the start date or end date selections, can change months & years with the arrows etc but not change the day.  It throws the exception:

2023-02-07 11:03:42.438 [AWT-EventQueue-1] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-1'
java.lang.NullPointerException: null
	at org.jdatepicker.impl.JDatePanelImpl$InternalTableCellRenderer.getTableCellRendererComponent(JDatePanelImpl.java:598) ~[evs-history-1.0.5.jar:na]
	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7037) ~[na:1.8.0_352]
	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7424) ~[na:1.8.0_352]
	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:6939) ~[na:1.8.0_352]
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184) ~[na:1.8.0_352]
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154) ~[na:1.8.0_352]
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685) ~[na:1.8.0_352]
	at javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:953) ~[na:1.8.0_352]
	at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1166) ~[na:1.8.0_352]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290) ~[na:1.8.0_352]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_352]

After throwing the exception, saving an edit in the complex property table worked fine.  Can't say at this time which if any operations are affected.

**Comment by bdionne** [comment] 2023-02-09 18:32
The error occurs when the user clicks on a number shown by the calendar, to change the date.

Looks like an issue in `jDatePicker`

**Comment by singhik** [comment] 2023-02-09 20:46
Tried above in Windows on 4.2.0-dev2 client, not readily reproducible but after leaving the UI idle for few mins and clicking on Execute ,did throw a revisionNull  header error , logs are attached [Logs.txt](https://github.com/NCIEVS/nci-protege5/files/10701351/Logs.txt)

**Comment by bdionne** [comment] 2023-02-09 20:49
Thanks @singhik , this is actually a different error. It's the socket timeout we've been seeing elsewhere. The autoupdater failed to get the head revision number.

**Comment by bdionne** [comment] 2023-02-09 21:27
Ok, this is a known [issue](https://github.com/JDatePicker/JDatePicker/issues/77) and looks to be fixed on master. I'll see if I can build and use their latest

**Comment by bdionne** [comment] 2023-02-28 14:31
A new tag [evs-history-1.0.6](https://github.com/NCIEVS/evs-history/releases/tag/evs-history-1.0.6) is available that fixes this

**Closed** 2023-07-13 18:24 UTC
Labels: bug, fixed, pass
