### ISSUE TITLE
GUI lock after loss of VPN connectivity

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#549] opened 2022-04-04 20:55 UTC
From [EHD 2022-03-29]

- Update error message caused GUI lock 
- 12:00 PM
- I had gotten an error when the VPN connection was briefly broken. (Did not screenshot this error.) Once the VPN reconnected, I selected Server>Update and got a blank error message (see attached screenshot). This window never displayed a message and could not be closed using the X at the top right. So I could not do anything with the GUI. 
-  I obtained a thread dump. Then I had to go to the dos console and type in Ctrl-C to exit protege and logged in again.

The log, a screenshot, and a thread dump are attached to the error report in the 3/29/22 12:25 PM (eastern) email.

**Comment by fragosog** [comment] 2022-11-03 20:18
Could not reproduce it.  Here's what I did:
- Connect to prod (currently 4.0.0)
- Wait for the "update" notice to show updates are in the server
- Disconnect VPN
- Wait 1-2 min to see protege error / exception
- Reconnect VPN
- Select Server->Update

Observations:
- I had a spontaneous hiccup (SocketTimeoutException) during the Wait step, same as the other ones we saw in UAT 4.1.0 arising from LocalHttpClient.postWithProjectId() during a Save action, but the popup was populated with "error while fetching the remote head...."
- On Disconnect I had the same populated popup "error while fetching..." but the log exception in this case was a java.net.UnknownHostException, and down in the stack trace the call was going through LocalHttpClient.postWithProjectId() as above.
- On Reconnect, protege picked up where it left, checking for updates.
- After 3 minutes of update checks I selected Server->Update, and the changeset update (4 changesets) ran without issues.

So no freezes or blank popups, but perhaps what we can do is catch the UnknownHostException and deal with it specifically, tentatively like in the suggestion for SocketTimeoutException, which could work on a spurious loss of VPN connectivity, but eventually bringing it up in a popup to the user advising them of the issue.

**Comment by singhik** [comment] 2022-12-13 22:37
@bdionne @fragosog  : The UnkownHostException due to loss of connectivity is logged in Protege logs and doing multiple edits and server updates with VPN Connects/Disconnects, did not cause GUI freeze , hence closing this ticket (4.2.0-dev1 build)

**Closed by singhik** 2022-12-13 22:37 UTC
Labels: bug, needs investigation, ready for QA, not reproducible
