### ISSUE TITLE
Save button does not become enabled, or is enabled but doesn't work

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#451] opened 2020-06-30 19:11 UTC
From [NS]:
"I have seen this happen during editing of modeling and PT edits. I get a model completed or I change a PT and the Save button does not become active. I have to log out and log back in and repeat the editing, then the Save button will be active and the edits can be saved. I see this at least once a day. (Note: [AG] has seen this sporadically as well.)"

From [EHD]:
"This seems similar to the issue I have seen in past versions when switching between editing in the Complex Edit tab and manual editing in the Edit tab but if [NS] is seeing this frequently in 3.3.0 with modeling or PT changes, maybe this issue can be more easily reproduced at this time."

From [AG]:
He "noted that sometimes the Save button is available but doesn't respond when you click on it. However, the GUI is not locked, he was able to use the Lucene Query Tab to do searches."

**Comment by NCIEVS** [comment] 2020-06-30 19:27
The frequency of the bug is too low.  The next time that this bug surfaces, we'd need access to the:
- protege.log, and 
- the time when the issue is noticed

**Comment by NCIEVS** [comment] 2020-06-30 19:30
From [AG]:
He sent a video of the Save button in this state.  Not when it happened, but rather after it was already in this state.

**Comment by bdionne** [comment] 2020-07-13 21:38
Still no logs or feedback from users. One small edge case was discovered that will be fixed in next EditTab tag, but doesn't appear related to save failures

**Comment by bdionne** [comment] 2020-07-14 09:51
AG reports the same issue, in this case when attempting to convert a class from primitive to defined. GUI beomes unresponsive and the conversion is unsuccessful and nothing gets saved. He needs to restart the app to proceed

**Comment by NCIEVS** [comment] 2020-07-14 11:33
Additional info from [AG] report (zipped log attached below):
- Loss of saving functionality. No option to save, unable to save changes
- failure at 15:35 ET, 2020-07-13
- Navigated to Refractory Acute Undifferentiated Leukemia C173503. Looked at the parents of the concept. Selected from the edit menu the option to convert from primitive to defined. Action not completed and interface gave no option to save. 
- Refractory Acute Undifferentiated Leukemia C173503 = primitive
- Had to restart to change from primitive to defined.

[protege2020.07.13-ag.zip](https://github.com/NCIEVS/nci-protege5/files/4918516/protege2020.07.13-ag.zip)

**Comment by bdionne** [comment] 2020-07-14 16:08
Thanks @NCIEVS - I saw this earlier and reviewed it. Here's a comment to made to AG in email about the issue:

> I think what might be happening is that many of these definitions are pretty involved and converting from primitive to defined moves a lot of things in that description panel. Protégé has implemented a lot of their own widgets at the level of the screen and mouse, rather than using standard Java widgets and things are breaking under the covers.

>Not sure why it breaks the save button yet, but I will find it.

What's happening is that the underlying `MList` is gone at this point, and some user interaction caused a paint event

**Comment by NCIEVS** [comment] 2020-07-15 19:50
New instance of bug from [NT]:
- Which operation failed? (such as Merge, Copy, Creation, PT changing)
Lost the save button
- Approximately what time did this failure occur?
July 15, 2:56 pm
- Description or sequence of steps followed:
Changed parent of a concept
- Concepts involved:
C126098
- If necessary, please include the state that the concepts were in at the time of the incident (e.g. edits of roles, defined/primitive changes). Screenshot is good if possible.
- Outcome (screen frozen, concept not created, had to log out and in to get things to work better):
had to log out and in to get things to work better

 Log file attached:
[protege-200715-256pm.zip](https://github.com/NCIEVS/nci-protege5/files/4927561/protege-200715-256pm.zip)

Skimming over the log, no ERROR, the typical WARN involving the OWLOntologyIRIMapper, and a WARN shown below 2 mins before the session ended

- 2020-07-15 09:12 session started
- 2020-07-15 14:56:17.670 [AWT-EventQueue-0] WARN  JOptionPaneEx    Component should implement VerifiedInputEditor for validating dialog to work. Using normal dialog with no validating
- 2020-07-15 14:58 session ended

**Comment by bdionne** [comment] 2020-07-16 18:00
This problem can be reproduced by using some sleeps in threads and reducing the autoupdate interval. It's similar to the [freezing bug](#440) in the code involved and there's a good chance it is fixed in the newest tags, `3.4.0-dev1` and `-dev2`

**Comment by singhik** [comment] 2020-07-31 19:50
@bdionne : 3.4.0-qa2



1. Amending or Adding a Parent to a Class, does not enable 'Save' button to Save the concept :: 

![image](https://user-images.githubusercontent.com/36314371/89071489-da2f6f00-d344-11ea-85e3-65124399de47.png)

![image](https://user-images.githubusercontent.com/36314371/89071497-e0255000-d344-11ea-94e2-b4aa2ba3296c.png)

2. Unable to 'Retire' and 'save' the Retired Concept as 'Save' button is not enabled to Save ::

![image](https://user-images.githubusercontent.com/36314371/89071616-1531a280-d345-11ea-8d2d-5af361c6b48a.png)

No Option to Save  the Retired COncept , only option works is to "Cancel' hence unable to Retire a concept

![image](https://user-images.githubusercontent.com/36314371/89071695-38f4e880-d345-11ea-8639-d0b0a44d45d8.png)

**Comment by bdionne** [comment] 2020-07-31 19:56
Is this a valid build? Have you verified you are running `3.4.0-qa2`?

**Comment by singhik** [comment] 2020-07-31 20:20
@bdionne : Attached is the screep print inside  the QA Server showing the Jenkins deployment from yesterday for 3.4.0-qa2, same is shown in the logs , have removed the username for sensitive data :: 

![image](https://user-images.githubusercontent.com/36314371/89074121-c803ff80-d349-11ea-8aa2-f43c3bc17eca.png)

**Comment by singhik** [comment] 2020-08-04 14:37
@bdionne : Hi, this ticket is blocked due to #460 .....

**Comment by singhik** [comment] 2020-08-06 18:34
Save button has been rigorously Tested for multiple scenarios of Load,Create,Retire, DUal Edits, Batch Load, Parent retree, Clone, Copy, Adding Simple and COmplex Properties,, No occurence of Save button being disabled or not working have been noted. Hence.closing the ticket as working fine on 3.4.0-qa2 build client

**Closed by singhik** 2020-08-06 18:34 UTC
Labels: bug, fixed, high priority, pass
