### ISSUE TITLE
allow ":" in preferred name

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#202] opened 2017-03-03 18:30 UTC

**Comment by bdionne** [comment] 2017-03-03 20:36
Allow both ":" and "@"

**Comment by NCIEVS** [comment] 2017-03-03 21:54
From EHD:  we want the colon for FULL_SYN and Preferred_Name/PT/label and we want the @ for FULL_SYN, DEF, ALT_DEF and DesignNote.

[I suppose we should allow : and @ for all properties; until this can become a configurable item]

**Comment by bdionne** [comment] 2017-03-08 20:40
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment] 2017-03-09 23:53
Hi,
I have retested and verified only partially of this fix using tag124. Currently, in NCI-Edittab-0.4.8, the right click menu drop down is unavailable on my local server. Please see attached screen shots for more details. This ticket still needs to be retested to validate adding definition, al definition and etc.  when the issue is resolved. In the meantime, please see attached screen shots for more details.


![issue 202 -1](https://cloud.githubusercontent.com/assets/8367102/23776031/acd0d64c-04f9-11e7-84d7-14b73bd1cfd4.png)
![issue 202 -2](https://cloud.githubusercontent.com/assets/8367102/23776033/aea6774c-04f9-11e7-85da-dd7303615073.png)

Thanks,
Reza

**Comment by rmehri** [comment] 2017-03-10 17:46
Hi Bob, 
I have retested this fix using "tag-125, nciedit-04.9" and verified  for the 
1) Adding Preferred_Name
2) Adding Definition and Alt Definition
3) Design Note for Merge, Retire
4) Editors Note (This was not on the list but it takes :@) --> Does this fix apply for Editors Note as well as Design Note? Please let me know. 

Please see attached zip file to see all the screen shots for more details:
[Screen Shots.zip](https://github.com/NCIEVS/nci-protege5/files/834683/Screen.Shots.zip)
Thanks,
Reza

**Comment by bdionne** [comment] 2017-03-10 18:32
it is on the list, see the comment above. The punctuation restrictions only apply to preferred_name

**Comment by rmehri** [comment] 2017-03-13 19:08
Hi Bob,

Are the following is part of the fix? 

"From EHD: we want the colon for FULL_SYN and Preferred_Name/PT/label and we want the @ for FULL_SYN, DEF, ALT_DEF and DesignNote.
[I suppose we should allow : and @ for all properties; until this can become a configurable item]"

Thanks,
Reza

**Comment by bdionne** [comment] 2017-03-13 20:37
this is the same ticket as #230

**Comment by bdionne** [comment] 2017-03-13 20:41
This is already fixed, just not yet pushed

**Comment by bdionne** [comment] 2017-03-15 14:57
fixed in th `0.5.0` version of `EditTab`

**Comment by rmehri** [comment] 2017-03-16 17:41
Hi, 
This fix has been retested and verified that ":" and "@", are allowed for preferred name only. 
I also received the correct warning message for "! and ?" 
Used the following servers:
http://localhost:8080
https://nciws-d699-v.nci.nih.gov:9090

Please see the attached screen shots:

![issue-202-1](https://cloud.githubusercontent.com/assets/8367102/24010322/e859672a-0a4d-11e7-9951-44c3ad00e430.png)
![issue-202-2](https://cloud.githubusercontent.com/assets/8367102/24010325/e9ecbcae-0a4d-11e7-9fef-57d0a05725c7.png)
![issue-202-3](https://cloud.githubusercontent.com/assets/8367102/24010330/ed9ef77c-0a4d-11e7-8698-80cc4024efe8.png)
![issue-202-4](https://cloud.githubusercontent.com/assets/8367102/24010335/f0edf8b0-0a4d-11e7-9f5d-ee04527b7c8f.png)

Thanks,
Reza

**Closed by rmehri** 2017-03-16 17:41 UTC
Labels: bug, fixed
