### ISSUE TITLE
Index loses sync - scenario involving deletion of property assertions

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#329] opened 2017-09-27 15:57 UTC
From [TQ]:
"I needed to delete a bunch of CDRH concepts, so I attached an editor note: NeedsCDRHCleanup to the terms. Then I manually deleted the FDA PTs and Alt Defs and Subsets and Concept has CDRH Parent values.

But, when I query such as Def Source contains FDA, they all still show up in the query results, but if you look at the individual concepts, there is no data to support this.

The same happens with the Full Syns, I do a search for term source contains FDA and they still show up.

Mind you, there are about 3 terms that still have an FDA PT because they belong to another group rather than CDRH, which is why I did the manual deletions.

Any ideas why this happens? It appears that they changes have not been registered with LQT. I shut down the program and went back in and the same results."

The above search issue itself was resolved after re-indexing the vocab.

**Comment by bdionne** [comment] 2017-09-27 16:09
This may be related to issues with preferences.

**Comment by NCIEVS** [comment] 2017-09-27 16:18
Do you think it's a setting that we can modify?

**Comment by bdionne** [comment] 2017-09-27 16:48
oh no, I'm not sure what this is exactly, need to investigate it. The incremental indexing seemed to work fine except occasionally, but worsened when we changed the preferences. On OS X it's gotten worse when we update the pellet client.

There's some problem with either the prefs, pellet, or the protege-client (autoupdater) that is interfering with the `LQT` thread. At least that's my guess, I don't think the issue is in the `LQT`

**Comment by bdionne** [comment] 2017-09-28 16:52
Ok, this is a bug, or at least missing functionality. The indexer is not properly updating the index with respect to qualifiers when a complex property is deleted.

**Comment by NCIEVS** [comment] 2017-11-01 20:33
Leaving this one as a medium high for the triage.  If somebody is doing QA on somebody else's work, they might not know that they need to reindex before they can get the same results back.

**Comment by bdionne** [comment] 2017-11-01 20:41
I've been debugging this one, it looks like the queries sent to the `indexWriter` that delete docs are failing. This happens on all deletions, .eg. object restrictions, it's not only annotations.

**Comment by bdionne** [comment] 2017-11-03 15:59
This is working better with an [upgrade to lucene 7.1.0](https://github.com/bdionne/lucene-search-tab/releases/tag/lucene-search-tab-1.1.1), but there are probably new issues to uncover. 

Deletes of annotations are now working.

**Comment by kondareddys2** [comment] 2017-12-01 15:38
The defect is fixed and tested in V2.1.010 Dev. Closing the defect.

**Closed by kondareddys2** 2017-12-01 15:38 UTC
Labels: bug, fixed, pass
