### ISSUE TITLE
Object Property & Annotation Property Add Buttons Missing - 3.6.0 Dev5 Code Base

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#502] opened 2021-04-06 17:58 UTC
Steps To Reproduce ::

Login to Protege Client version 3.6.0-dev5  with a Manager Role .
Navigate to 'Windows'->'Tabs'->Object Properties/Annotation Properties  Tab(s) .

Expected ::

Object Properties and Annotation Properties Tabs should show 'Sub' & 'Sibling' properties addition buttons allowing addition and Deletion of Properties for a 'Manager Role' 

Actual ::

Object Properties and Annotation Properties Tab do not show addition or deletion property buttons 

![image](https://user-images.githubusercontent.com/36314371/113753980-bd6de700-96dc-11eb-8829-b59b7e03df35.png)

![image](https://user-images.githubusercontent.com/36314371/113754035-c959a900-96dc-11eb-8a2a-305cde231610.png)

**Comment by bdionne** [comment] 2021-04-15 17:52
Not able to reproduce, @singhik does this happen consistently every time you log in? I noticed in the screenshots you opened these views separately rather than just enabling the entities tab, which opens them all (this is fine), but I'm able to do that also with no problem.

One way this will happen for sure is if the login is not a manager, so if you're positive that's the case, the most likely suspect is the fileprefs

**Comment by bdionne** [comment] 2021-06-16 16:15
I'm unable to reproduce this, but I do note that if I login with a user who is a workflow modeler and *not* a workflow manager, I can see that the buttons are disabled, as they should be.

**Comment by safrant** [comment] 2021-06-16 18:04
- If I have a user with only the manager role assigned then I see the Add Properties button is visible
- I then logout of user and go to admin tool to add a role to the user.  I then close the tool
- I log back in with user to editor and add buttons are missing
- I log out and delete the .fileprefs
- I log back in and the add buttons are present

**Comment by bdionne** [comment] 2021-06-17 14:47
One scenario that reproduces is when the user logouts using `server/logout` after making changes using an admin login, and then `file/open from server` to reopen the project.

If the object properties or annotations properties tabs are opened, the buttons are lost.

Note that you can fix them by just deleting the tab and exposing it again.

The next build, `3.7.0-qa1` has a fix for this

**Comment by safrant** [comment] 2021-08-19 19:44
This looks like a privilege issue. My account  had both modeler and manager roles assigned.  If modeler removed it worked.

**Comment by bdionne** [comment] 2021-08-23 17:26
We need to revisit privileges and take into account users having multiple roles and exclusions based on projects.

Consider login-as for a new operation

**Comment by NCIEVS** [comment] 2022-04-18 18:23
@bdionne I was thinking that since the manager can do everything a modeler can, could we just disallow both manager and modeler roles assigned to the same person?  Can be one or the other but not both.  But is it possible that in general there could be issues when the same user has multiple roles, for instance manager and administrator?

**Comment by singhik** [comment] 2022-12-05 22:33
@bdionne  : Hi, what is the fix applied to this ticket ? Is it to not allow same user having both Manager & Modeler Roles ?

**Comment by bdionne** [comment] 2022-12-08 21:56
> Is it to not allow same user having both Manager & Modeler Roles ? - @singhik 

No, a user can have both roles.

**Comment by fragosog** [comment] 2023-01-05 19:34
Well, finally got around to testing this, but I'm not getting "buttons missing" in the property tabs (annotation & object props) unless I'm using guest or sysadmin role.  The guest role should not behave like this, you should be able to get the gui but it should be read-only, instead I only see the "individuals by class" tab (and exceptions, in sysadmin as well) and can't open any other tab.  

| role(s) | buttons visible? |
| --- | --- |
| Workflow Manager | yes |
| Workflow Modeler | yes |
| Administrator | yes |
| Sysadmin | exceptions, gui IBC only, reprdced |
| Guest | exceptions, gui IBC only |
| Administrator, Sysadmin | yes |
| Administrator, Workflow Manager | yes |
| Workflow Manager, Workflow Modeler | yes |
| Administrator, Sysadmin, Workflow Manager | yes |

**Comment by bdionne** [comment] 2023-01-06 15:15
Per conversation yesterday, this table to have a column added and expected versus actual behavior documented (@singhik )

@bdionne will then fix discrepancies

**Comment by singhik** [comment] 2023-01-25 02:18
@bdionne @fragosog  : Hi, i have performed tests with below results on 4.2.0-dev2 , as per me only 'sysAdmin' is not as Expected, pleae review : 

![image](https://user-images.githubusercontent.com/36314371/214465736-d88e3233-2835-4eff-81d4-21ca213de895.png)


[Logs-sysAdmin.txt](https://github.com/NCIEVS/nci-protege5/files/10495573/Logs-sysAdmin.txt)

**Comment by singhik** [comment] 2023-01-27 00:58
@fragosog @bdionne : As discussed in 1/26/2023 's connect, 'SysAdmin' role is only meant to login into Administrator Panel and hence the above scenario is Red can be marked N/A . 
Hence this ticket can be closed for now and If the attached logs look suspicious ,it can be looked in the future .

**Comment by bdionne** [comment] 2023-03-15 21:09
closed per last comment

**Closed by bdionne** 2023-03-15 21:09 UTC
